### ISSUE TITLE
using linq in razor template 

### ISSUE THREAD

**Issue by talarari** [Antaris/RazorEngine#115]
hey, 
upgraded from version 2 to 3.2 
this used to work
@Model.SomeList.Sum(a =>  a.Amount)

now i get this exception:
Unable to compile template. Cannot use a lambda expression as an argument to a dynamically dispatched operation without first casting it to a delegate or expression tree type

works if i do this:
@((MySpecificModelType)Model).SomeList.Sum(a =>  a.Amount)

why does this happen? anyway of using Sum without casting?

thanks!

**Comment by huangyedie** [comment]
![image](https://user-images.githubusercontent.com/51399090/224951861-0aa70410-4200-450a-a611-134e89a4bee6.png)

Why there is no 3.3 version of this

**Comment by huangyedie** [comment]
@coxp
