### ISSUE TITLE
Cannot use from IronPython script - "Template is required"

### ISSUE THREAD

**Issue by charlesjwalker** [Antaris/RazorEngine#122]
I have a C# class library that uses RazorEngine internally.  This library works great when invoked from a C# console application or website code.  However, when I invoke this library from an IronPython script, RazorEngine always throws a "Template is required" exception.  This also happens if I invoke RazorEngine directly within the IronPython script.  Here's an example script:

C# code that works:

    using RazorEngine;
    namespace ConsoleApplication5
    {
        class Program
        {
            static void Main(string[] args)
            {
                Razor.Compile("Hello World!", "MyTemplate");
                var resolvedTemplate = Razor.Resolve("MyTemplate");
            }
        }
    }

IronPython code that throws a "Template is required" exception in the "Resolve" call:

    import clr
    clr.AddReferenceToFile("RazorEngine.dll")
    from RazorEngine import Razor

    Razor.Compile("Hello World!", "MyTemplate")
    resolvedTemplate = Razor.Resolve("MyTemplate")  #throws "Template is required" error

What am I missing for this to work from Iron Python?

**Comment by matthid** [comment]
Any chance of a repro. I did not manage to get Ironpython do anything :(

**Comment by matthid** [comment]
I'll close this for now (and reopen if there is any activity/interest).
