### ISSUE TITLE
Layout support

### ISSUE THREAD

**Issue by danpowell88** [Antaris/RazorEngine#128]
What is the @layout support in RazorEngine, the codeplex site seems to say it wasn't done but was going to be added at some point.

I'm wanting to use actionmailer.net and see they had a commit that in 3.2.0 layouts are supported.

Does it work the same as normal razor layouts

ie. specify (in a view)
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

is the viewstart.cshtml supported?

How do you render sections, is it still @RenderSection("adsf") and @RenderBody

Cheers

**Comment by litera** [comment]
Is this still the case or do newer versions of RazorEngine precompile layout templates?

**Comment by matthid** [comment]
You can tell RazorEngine to precompile template anytime you want by using `Compile` and `Run` instead of `RunCompile` (which compiles templates when they are used). For layouts you can use `Compile` as well to precompile.

**Comment by ludmal** [comment]
Honestly, dissapointed about the documentation.. no updates for versions. And the main use of using Razor templating is that you can priovide layout page and that's no where to be found in the documentation. Documentation must be focused on what is important not what it can do if you are not ready to provide a comprehensive guide. Spent hours trying to figure out Layout implementation and left! Also the basic mistake most of the developers do is must keep things simple. Simple things must be simple and library should be extensible! which is does of course but lack simplicity.
