### ISSUE TITLE
Stack empty.

### ISSUE THREAD

**Issue by fitzchak** [Antaris/RazorEngine#136]
System.InvalidOperationException occurred
  _HResult=-2146233079
  _message=Stack empty.
  HResult=-2146233079
  IsTransient=false
  Message=Stack empty.
  Source=System
  StackTrace:
       at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
  InnerException: 

On this line:

```
    /// <summary>
    /// Pops the template writer helper off the stack.
    /// </summary>
    /// <returns>The template writer helper.</returns>
    internal TemplateWriter PopBody()
    {
        return _bodyWriters.Pop(); // here: _bodyWriters.Length is 0
    }
```

**Comment by themidnightgospel** [comment]
Same error happens when `@@RenderSection` is called **Inside** section.
