### ISSUE TITLE
Form Submit issue

### ISSUE THREAD

**Issue by pxg804** [Antaris/RazorEngine#150]
The form renders fine, however on the submission the form data is not returned, what am I missing, template shown below:

<form action="/" method="post">
  <fieldset>
    <legend>Member Information</legend>
      <p>
        <label for='FirstName'>First Name</label>
        <input class='text-box single-line' id='FirstName' name='FirstName' type='text' value='@Model.FirstName' />
      </p>
  </fieldset>
  <br />
  <input type="submit" value="Submit" /> 
</form>

**Comment by leojh** [comment]
I can't get BeginForm to compile. I get the 'HtmlHelper does not contain definition or extension method for BeginForm'... how do I get the engine to reference the extension method?

**Comment by antscode** [comment]
My guess is that you have not included the System.Web.Mvc namespace in your default namespaces. When defining your TemplateService, try defining your namespaces, e.g.

        private static readonly TemplateService _templateService = new TemplateService(new TemplateServiceConfiguration
        {
            BaseTemplateType = typeof(MyTemplateBase<>),
            Resolver = new MyTemplateResolver(),
            Namespaces = new HashSet<string>(new string[] { 
                "System", 
                "System.Collections", 
                "System.Collections.Generic",
                "System.Globalization",
                "System.Linq",
                "System.Web",
                "System.Web.Mvc", 
                "Whatever.Else"
            })
        });

**Comment by leojh** [comment]
@antscode That did it. Thank you!

**Comment by ImaginaryDevelopment** [comment]
does this mean there is a way to get Html.BeginForm, and Html.Raw to work? can someone share a sample link?
