### ISSUE TITLE
RazorEngine escapes HtmlString values

### ISSUE THREAD

**Issue by bifacil** [Antaris/RazorEngine#166]
Razor should not escape HtmlString values, and it does. You can test it:

```
Debug.WriteLine(RazorEngine.Razor.Parse("@Model",New System.Web.HtmlString("<h1>Hello!</h1>")))
```

It should return:

```
<h1>Hello!</h1>
```

But it returns:

```
&lt;h1&gt;Hello!&lt;/h1&gt;
```

I know that it works using RazorEngine.Text.RawString, but I think it should work using the .Net type.

More info: http://stackoverflow.com/questions/6216340/always-output-raw-html-using-mvc3-and-razor

**Comment by fredericDelaporte** [comment]
This is the n°1 issue on this site, with as a response another way of handling that, provided by the author Antaris. See  [his suggested solution here](https://github.com/Antaris/RazorEngine/issues/1#issuecomment-2795908). It is about `MvcHtmlString` but can easily be changed to handle `IHtmlString` instead, which is implemented by `HtmlString` and `MvcHtmlString`.
