### ISSUE TITLE
Consider dual-licensing under Apache 2.0?

### ISSUE THREAD

**Issue by nathanaeljones** [Antaris/RazorEngine#190]
The MS-PL is incompatible with many free software licenses, as it imposes a unique restriction:

> (D) If you distribute any portion of the software in source code form, you may do so **only under this license** by including a complete copy of this license with your distribution. [...]

Many OSI-approved copyleft licenses require that linking or interacting code must be licensed in a manner that does not further restrict user rights. This conflicts with the MS-PL as it specifically prohibits the right to re-license.

There are many GPL, LGPL, and AGPL-licensed libraries - yet we are forced to choose between using them - and using this library. We are also prevented from using any copyleft license in software which depends on RazorEngine.

Dual-licensing (or-relicensing) under Apache 2 would solve this. As GitHub notifies people who are mentioned, re-licensing would involve pasting the list of contributors into this thread and asking for a release of their copyright. Getting approval can take anywhere from a few days to several months, depending upon contributor awareness. 

Thoughts?

**Comment by matthid** [comment]
I hereby release all of my contributions to this project under the terms of the Apache 2 license.

@nathanaeljones You mean @7sharp9 instead of sharp9 (https://github.com/Antaris/RazorEngine/graphs/contributors)?
I tried to write emails to @scottnickel, @dalenewman and @mehdime as they seem to be no longer active on github. @7sharp9 may have missed it as he was not mentioned before.

**Comment by 7sharp9** [comment]
I didn't get notified before, did I do any contributions anyway?

I hereby release all of my contributions to this project under the terms of the Apache 2 license.

**Comment by dalenewman** [comment]
I hereby release all of my contributions to this project under the terms of the Apache 2 license.

**Comment by kipwilliams** [comment]
I hereby release all of my contributions to this project under the terms of the Apache 2 license.

**Comment by matthid** [comment]
ping @mehdime @scottnickel

**Comment by matthid** [comment]
In the history on codeplex I additionally found @Buildstarted. Could you please sign-off the license change as well? Besides that we are on a good way: All currently missing commits can be reverted if we need to. I will wait a little longer and then execute the change and revert all commits from outstanding people (and re-implement missing features).

**Comment by matthid** [comment]
Thanks all for signing off the license change!
This is now released in https://www.nuget.org/packages/RazorEngine/3.7.0-beta1. Please test and report if I broke anything.
