### ISSUE TITLE
Documentation doesn't match latest NuGet package

### ISSUE THREAD

**Issue by elneilios** [Antaris/RazorEngine#212]
I just noticed that a new version has been published to NuGet only the documentation doesn't explain how to use the new API. Specifically it wasn't clear how to use the new Template caching

**Comment by matthid** [comment]
Do you mean [this](https://antaris.github.io/RazorEngine/Caching.html)?
Any change to be more concrete or directly sending a pull request to https://github.com/Antaris/RazorEngine/blob/develop/doc/Caching.md?

**Comment by elneilios** [comment]
Nope, I mean this: http://antaris.github.io/RazorEngine/

The quick start code doesn't match the method signatures in the latest NuGet version. E.g. I can't provide a string for the templateKey in RunCompile, it's not an ITemplateKey type

**Comment by matthid** [comment]
Ah because those are extension methods and you need to open the RazorEngine.Templating namespace, this is tricky now. Thank you for the hint I will add that to the docs.

**Comment by matthid** [comment]
The docs are now updated. Thanks again for reporting.

**Comment by elneilios** [comment]
Ahh I see, thanks for the info
