### ISSUE TITLE
The name 'Model' does not exist in the current context

### ISSUE THREAD

**Issue by elneilios** [Antaris/RazorEngine#213]
I am using RazorEngine in a WPF application and have created a .cshtml file for my template. However I get a lot of errors in the VS2013 designer as shown in the issue title (see screenshot below). The project builds and runs OK but Is there a way to make the designer happy with my .cshtml file?

![image](https://cloud.githubusercontent.com/assets/1699463/5755197/899c5ab8-9c99-11e4-8370-9ffe1dbb8f72.png)

**Comment by matthid** [comment]
You can try one of the answers of http://stackoverflow.com/questions/26862336/how-to-make-intellisense-works-with-razorengine? Either one should work, just note that for the `app.config` solution you do not get intellisense for a custom base class (if you use one).

Another example (with a custom base class) is here: https://antaris.github.io/RazorEngine/IntellisenseAndResharper.html (note: the Model property is not required as it is already in the base class)

**Comment by elneilios** [comment]
Thanks for those links. I didn't want to bloat the application by including the MVC assemblies so I went with the later solution. This is the class I created:

    public class RazorEngineTemplate<T> : TemplateBase<T>
    {
        public new T Model 
        {
            get { return base.Model; }
            set { base.Model = value; }
        }
    }

I had to add an overriding Model property because the cshtml designer couldn't find TemplateBase.Model for some reason and still showed the error

**Comment by matthid** [comment]
That should work. Do you use Resharper?
Because without Resharper `@inherits TemplateBase<MyModel>` is working for me.

**Comment by elneilios** [comment]
I did try that first but for some reason the designer could not resolve the RazorEngine assembly, even though it is referenced in the project that the cshtml file resides in

**Comment by matthid** [comment]
You are right... after looking into this a bit more I found another solution in http://stackoverflow.com/questions/4953330/razor-based-view-doesnt-see-referenced-assemblies. 

If you change the project settings to build into `bin\` instead of `bin\Debug` and `bin\Release` it will work. I assume it would also work if you would copy all project references into the `bin\` directory.

You don't need any custom base class in this case (it will work with TemplateBase<>). I try to add this to the docs.

**Comment by matthid** [comment]
I updated the docs in https://antaris.github.io/RazorEngine/IntellisenseAndResharper.html. Please tell me if it doesn't work as described there (and my last post).

**Comment by elneilios** [comment]
Interesting, I wonder if its because a normal MVC application wouid output to `bin\` rather than `bin\Debug` etc? Maybe the VS designer is always expecting to find the assemblies there?

**Comment by matthid** [comment]
Yes that's what I'm thinking as well. I have no idea if this is hard-coded or can be changed somewhere (I didn't found any hint for that though).
