### ISSUE TITLE
error: (18, 21) 命名空间“ComXXX”中不存在类型或命名空间名称“Config”(是否缺少程序集引用?) 

### ISSUE THREAD

**Issue by longjxchina** [Antaris/RazorEngine#214]
other namespace can import by use like:@using ComXXX.Business, only Config namespace can't import in cshtml

**Comment by longjxchina** [comment]
other namespace can import by use like:@using ComXXX.Business, only Config namespace can't import in cshtml

**Comment by matthid** [comment]
I need more info to help you out:
- Did it work in previous versions of RazorEngine?
- minimal testcase/example that fails.

Maybe https://antaris.github.io/RazorEngine/index.html#Set-a-reference-resolver helps?

**Comment by longjxchina** [comment]
i found: I only used ComXXX.Config const filed value,then AppDomain.GetAssemblies don't get ComXXX.Config  assembly

**Comment by matthid** [comment]
I can only make a guess without more information, please try to write a minimal testcase as requested in my first post.
- Is `typeof(ComXXX.Config.Type).Assembly == typeof(ComXXX.Business.Type).Assembly`?
- Is `typeof(ComXXX.Config.Type).Assembly.Location == null`?
- Can you verify that the `ComXXX.Config` assembly is actually loaded before compiling the template?
- Try to set the resolver manually (link in my previous post).
