### ISSUE TITLE
Duplicate assembly imports give error - GetReferences() method is really hard (impossible?) to use properly

### ISSUE THREAD

**Issue by PhilipDaniels** [Antaris/RazorEngine#219]
Trying to compile Lithogen.TestSite2 results in the error:

    An assembly with the same identity 'XXX' has already been imported. Try removing one of the duplicate references.

This is a message from the compiler and can be produced when using the naive FirstRazorEngineReferenceResolver.

In comparison, Lithogen.TestSite1 will build OK. The difference - I have removed most references from TestSite1 so the bin folder only has Lithogen.TestSite1.dll in it. So how not to return duplicates? We have to check in the loadedAssemblies collection, which is very hard.

I make an attempt in the class SecondRazorEngineReferenceResolver, only to get "The name 'Html' does not exist in the current context." Note that this class is really horrible and poor code, and I am only testing one of the concrete subtypes! A robust solution would check them all. The base class has no useful information on it which clients can use.

Some points:
1. I don't understand why you are asking me to return the references from UseCurrentAssembliesReferenceResolver().
   Surely you should already know about them?
2. The API is really hard to use. How are we supposed to find the duplicates? The hack in SecondRazorEngineReferenceResolver is really poor, takes no account of versions.
3. You should de-duplicate references in your code, not expect clients to deal with it.
4. Please put some DebuggerDisplay attributes on the classes so we can see what we are dealing with.
5. I don't know what the includeAssemblies parameter is for.

----
Steps to reproduce:

git clone https://github.com/PhilipDaniels/Lithogen
git checkout 4fd5a5c29916d82cc0ac6bc11085aeec18912fe3  # Version known to have problem.
Run the command install_npm_modules.cmd
Rebuild Lithogen.TestSite2

You can put a breakpoint in the RazorProcesser and debug in the normal way. You may need to set the command line parameters for the Lithogen program to (or similar):
  --config=C:\Users\Phil\repos\Lithogen\src\Lithogen.TestSite2\bin\Lithogen.xml

**Comment by matthid** [comment]
I think the problem you are running into is the following:
When you first compile a template your custom assemblies are not loaded and therefore not returned.
In the second run they are loaded and therefore returned.

There are multiple ways to approach this
- RazorEngine uses https://github.com/Antaris/RazorEngine/blob/master/src/source/RazorEngine.Core/Compilation/ReferenceResolver/UseCurrentAssembliesReferenceResolver.cs to prevent duplicates
- Don't return all items from `UseCurrentAssembliesReferenceResolver` but only the ones you need
- Don't use the `UseCurrentAssembliesReferenceResolver` at all and build up your own list (which I would recommend in your situation)

It can be done like this:

```csharp
public IEnumerable<CompilerReference> GetReferences
(
RazorEngine.Compilation.TypeContext context,
IEnumerable<CompilerReference> includeAssemblies = null
)
{
  // Add all basics you need
  yield return CompilerReference.From(typeof(int).Assembly);
  yield return CompilerReference.From(typeof(System.Linq.Enumerable).Assembly);
  yield return CompilerReference.From(typeof(Binder).Assembly);
  
  // Add your own things
}
```

1. I don't ask you too, that's the whole point of the API that you can decide what's used for compilation.
2. See above.
3. I'm not sure I understand this point.
4. Can you send a pull request for this?
5. That's a list of assembly requested by the compiler to put in (Microsoft.CSharp for C# for example), you need this only if you want to support multiple template languages with your resolver.

**Comment by PhilipDaniels** [comment]
You can close this request, I have a workaround. My ModelFactory will be loading all the assemblies into my AppDomain before I ever call you, so just returning the current assemblies will work.

The subsequent problem, about "Html", is an issue with MVC helpers, which is explained on your AboutRazor page. (I have submitted a pull request to fix a couple of typos).

**Comment by matthid** [comment]
Yeah sorry for not listing up that (pre 3.5.x) method. I thought there was a reason you need to use the IReferenceResolver (for example mono compatibility).

Glad that it now works for you!
