### ISSUE TITLE
Impromptu Razor Namespace conflicts with ImpromptuInterface framework

### ISSUE THREAD

**Issue by kipwilliams** [Antaris/RazorEngine#221]
Because Razor's Impromptu namespace is top level it can't be reference alongside the ImpromptuInterface assembly from nuget in the same project.

**Comment by matthid** [comment]
I'm a bit busy the next weeks, would you step up and do the internalizing and(/or?) refactoring and send a pull request? I would quickly review, accept and release it in the nuget package when it's finished. Thanks for reporting,

**Comment by kipwilliams** [comment]
I have submitted a pull request for you.

**Comment by matthid** [comment]
Thanks! I'm closing this then (Fixed with #222).
