### ISSUE TITLE
Why is it not possible to resolve a ITemplate?

### ISSUE THREAD

**Issue by TryingToImprove** [Antaris/RazorEngine#225]
I dont understand why it not possible to resolve a `ITemplate` with RazorEngine. The `TemplateService` is marked as obsolete but it has a `Resolve`-method.

Anyone that can comment on this?

**Comment by matthid** [comment]
Can you elaborate the reasons why you need access to instances of that interface directly?
I decided to remove direct access to it as it isn't easy to use and mostly doesn't do what you think it does. It also can cause problems in case you use the Isolation API.

**Comment by TryingToImprove** [comment]
I use it to resolve a Layout, with a different model, than whats it is the `Model`-property on my `DefaultTemplateBase`;

Here is what I do..


    namespace Application.Templating
    {
        public class DefaultTemplateBase<T> : TemplateBase<T>
        {
            private static readonly List<PageRouteView> Routes = new List<PageRouteView>();

            private readonly DataAccessor _dataAccessor;

            private TemplateViewData _templateViewData;

            public DefaultTemplateBase()
            {
                _dataAccessor = ObjectFactory.GetInstance<DataAccessor>();
            }

            public ILocalizer Localizer { get; set; }

            public override void SetModel(object model)
            {
                // The viewmodel passed to the template
                _templateViewData = (TemplateViewData)model;

                // We need a localizer, so we can localize the text, so we can write @Localizer.GetText() instead of @Model.Localizer.GetText()
                Localizer = new DatabindedLocalizer(_dataAccessor, _templateViewData.Language);

                // Set the main model
                base.SetModel(_templateViewData.Model);
            }

            protected override ITemplate ResolveLayout(string name)
            {
                // We need to resolve the ITemplate with the TemplateViewData instead of the model, otherwise, the SetModel on the Layout will fail
                return TemplateService.Resolve(name, _templateViewData);
            }
        }
    }

    public class TemplateViewData
    {
        public string Language { get; set; }

        public object Model { get; set; }
    }

**Comment by matthid** [comment]
Hm does something like that work on MVC?
Several possible solutions come to my mind:

* use `InternalTemplateService.Resolve(name, _templateViewData, typeof(T), ResolveType.Layout);`
  This is basically the new API used in such template `internal` scenarios.
  Example:
  ```csharp

    public class DefaultTemplateBase_OverrideInclude<T> : TemplateBase<T>
    {
        private readonly DataAccessor _dataAccessor;

        private TemplateViewData _templateViewData;
        public DefaultTemplateBase_OverrideInclude()
        {
            _dataAccessor = ObjectFactory.GetInstance<DataAccessor>();
        }

        public ILocalizer Localizer { get; set; }

        public override void SetModel(object model)
        {
            // The viewmodel passed to the template
            _templateViewData = (TemplateViewData)model;

            // We need a localizer, so we can localize the text, so we can write @Localizer.GetText() instead of @Model.Localizer.GetText()
            Localizer = new DatabindedLocalizer(_dataAccessor, _templateViewData.Language);

            // Set the main model
            base.SetModel(_templateViewData.Model);        
        }

        public override TemplateWriter Include(string cacheName, object model = null, Type modelType = null)
        {
            // When model == null we use our current model => we should use the same modelType as well.
            return base.Include(cacheName, model ?? _templateViewData, model == null ? typeof(T) : modelType);
        }

        protected override ITemplate ResolveLayout(string name)
        {
            // We need to resolve the ITemplate with the TemplateViewData instead of the model, otherwise, the SetModel on the Layout will fail
            return InternalTemplateService.Resolve(name, _templateViewData, typeof(T), ResolveType.Layout);
        }
    }

  ```
  Usage:
  ```csharp
        [Test]
        public void RazorEngineService_CustomLocalizerHelper_OverrideInclude()
        {
            RunTestHelper(service =>
            {
                var model = new TemplateViewData() { Language = "lang", Model = new Person() { Forename = "forname", Surname = "surname" } };
                var template = @"@Model.Forename @Include(""test"") @Localizer.Language";

                service.Compile("@Model.Surname", "test", typeof(Person));
                string result = service.RunCompile(template, Guid.NewGuid().ToString(), typeof(Person), model);
                Assert.AreEqual("forname surname lang", result);
            }, config =>
            {
                config.BaseTemplateType = typeof(DefaultTemplateBase_OverrideInclude<>);
            });
        }

  ```

* I played with the idea of

  ```csharp

    // Depends on internal API
    public class DefaultTemplateBase_OverrideModelType<T> : TemplateBase<TemplateViewData>
    {
        private readonly DataAccessor _dataAccessor;

        public DefaultTemplateBase_OverrideModelType()
        {
            _dataAccessor = ObjectFactory.GetInstance<DataAccessor>();
        }

        public new T Model { get { return (T)base.Model.Model; } }
        internal override Type ModeType
        {
            get
            {
                return typeof(T);
            }
        }

        public ILocalizer Localizer { get; set; }

        public override void SetModel(object model)
        {
            // Set the main model
            base.SetModel(model);

            // We need a localizer, so we can localize the text, so we can write @Localizer.GetText() instead of @Model.Localizer.GetText()
            Localizer = new DatabindedLocalizer(_dataAccessor, base.Model.Language);
        }
    }
  ```
  But I would need to make the ModelType property public.
  Usage:
  ```csharp
        [Test]
        public void RazorEngineService_CustomLocalizerHelper_OverrideModelType()
        {
            RunTestHelper(service =>
            {
                var model = new TemplateViewData() { Language = "lang", Model = new Person() { Forename = "forname", Surname = "surname" } };
                var template = @"@Model.Forename @Include(""test"") @Localizer.Language";

                service.Compile("@Model.Surname", "test", typeof(Person));
                string result = service.RunCompile(template, Guid.NewGuid().ToString(), typeof(Person), model);
                Assert.AreEqual("forname surname lang", result);
            }, config =>
            {
                config.BaseTemplateType = typeof(DefaultTemplateBase_OverrideModelType<>);
            });
        }
  ```
  I like that option more but I'm not sure of the consequences of making that API public (and its miss-uses)

* Another way would be to use Viewbag:
  ```csharp
    public class DefaultTemplateBase_Viewbag<T> : TemplateBase<T>
    {
        private readonly DataAccessor _dataAccessor;
        private ILocalizer _localizer;

        private TemplateViewData _templateViewData;
        public DefaultTemplateBase_Viewbag()
        {
            _dataAccessor = ObjectFactory.GetInstance<DataAccessor>();
        }

        public ILocalizer Localizer { 
            get {
                if (_localizer == null)
                {
                    _localizer = new DatabindedLocalizer(_dataAccessor, ViewBag.Language);
                }
                return _localizer;
            }
        }
    }
  ```
  It's the simplest but has the problem that the ViewBag is not available in the SetModel method (which is not a problem but it changes the logic a bit), I will evaluate this and probably allow access to the Viewbag in the SetModel method in future versions!

  Usage:
  ```csharp
        [Test]
        public void RazorEngineService_CustomLocalizerHelper_ViewBag()
        {
            RunTestHelper(service =>
            {
                var model = new Person() { Forename = "forname", Surname = "surname" };
                var template = @"@Model.Forename @Include(""test"") @Localizer.Language";

                service.Compile("@Model.Surname", "test", typeof(Person));
                dynamic viewbag = new DynamicViewBag();
                viewbag.Language = "lang";
                string result = service.RunCompile(template, Guid.NewGuid().ToString(), typeof(Person), model, (DynamicViewBag) viewbag);
                Assert.AreEqual("forname surname lang", result);
            }, config =>
            {
                config.BaseTemplateType = typeof(DefaultTemplateBase_Viewbag<>);
            });
        }
  ```
  
All in all I would suggest you to use the Viewbag option. You can use the first option as well but I planned to get rid of that API as well (as soon as I come up with a good idea to do so). You cannot really use the second option right now (if you do not compile RazorEngine yourself) but I think it would be the cleanest approach.

Hope this helps.

**Comment by TryingToImprove** [comment]
Thanks for the help.. :+1: I will look into using the `ViewBag` solution.. :)
