### ISSUE TITLE
Compilation errors due to missing references v3.5.3

### ISSUE THREAD

**Issue by coreyperkins** [Antaris/RazorEngine#233]
Anybody know how to deal with this? I'm not sure how to implement the IReferenceResolver to include System.Web.Mvc.HtmlHelper. I thought using the WebViewPage<> type for the BaseTemplateType to get @Html support would fix this. It also doesn't matter if I use a custom model in my own assembly or the DynamicObject. I still get the same errors surrounding HtmlHelper.

Errors while compiling a Template.
Please try the following to solve the situation:
  * If the problem is about missing references either try to load the missing references manually (in the compiling appdomain!) or
    Specify your references manually by providing your own IReferenceResolver implementation.
    Currently all references have to be available as files!
  * If you get 'class' does not contain a definition for 'member': 
        try another modelType (for example 'null' or 'typeof(DynamicObject)' to make the model dynamic).
        NOTE: You CANNOT use typeof(dynamic)!
    Or try to use static instead of anonymous/dynamic types.
More details about the error:
 - error: (37, 24) 'System.Dynamic.DynamicObject' does not contain a definition for 'ClientName' and no extension method 'ClientName' accepting a first argument of type 'System.Dynamic.DynamicObject' could be found (are you missing a using directive or an assembly reference?)
     - error: (41, 23) 'System.Web.Mvc.HtmlHelper<System.Dynamic.DynamicObject>' does not contain a definition for 'Label' and no extension method 'Label' accepting a first argument of type 'System.Web.Mvc.HtmlHelper<System.Dynamic.DynamicObject>' could be found (are you missing a using directive or an assembly reference?)
     - error: (47, 19) 'System.Web.Mvc.HtmlHelper<System.Dynamic.DynamicObject>' does not contain a definition for 'LabelFor' and no extension method 'LabelFor' accepting a first argument of type 'System.Web.Mvc.HtmlHelper<System.Dynamic.DynamicObject>' could be found (are you missing a using directive or an assembly reference?)
     - error: (53, 19) 'System.Web.Mvc.HtmlHelper<System.Dynamic.DynamicObject>' does not contain a definition for 'TextBoxFor' and no extension method 'TextBoxFor' accepting a first argument of type 'System.Web.Mvc.HtmlHelper<System.Dynamic.DynamicObject>' could be found (are you missing a using directive or an assembly reference?)

Here's my code:

var config = new RazorEngine.Configuration.TemplateServiceConfiguration();
            // config.BaseTemplateType = typeof(RazorEngine.Templating.HtmlTemplateBase<>);
            config.BaseTemplateType = typeof(WebViewPage<>);
            config.ReferenceResolver = new RazorEngine.Compilation.ReferenceResolver.UseCurrentAssembliesReferenceResolver();

            using (var service = new RazorEngine.Templating.TemplateService(config)) {
                var fileBasePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"views\identityview");
                var file = Path.Combine(fileBasePath, "Consent" + ".cshtml");
                var razorTemplate = File.ReadAllText(file);

                RazorEngine.Razor.SetTemplateService(service);

                var result = service.Parse(razorTemplate, model, null, null);
            }

**Comment by matthid** [comment]
Even when you get it to compile (which is very unlikely) it would fail anyway as the TemplateBase type is expected to implement the `ITemplate` interface which `WebViewPage<>` clearly doesn't implement.
To extend the syntax with `@Html` read the guide in https://antaris.github.io/RazorEngine/TemplateBasics.html#Extending-the-template-Syntax . This is the only supported way of extending the syntax. That said you could use the compilation API to compile and load a template with `WebViewPage<>` but then you need to build up your own version of `RazorEngineService` which is most likely very hard - if not impossible - because of access rights and internal only API.

**Comment by coreyperkins** [comment]
Interesting, thanks for the pointer, that helped me to understand better how to extend the base syntax. The tricky part for me appears to be that I need the Html property in the HtmlSupportTemplateBase to be a System.Web.Mvc.HtmlHelper. I'll need to figure out how that possible.
