### ISSUE TITLE
Can't seem to get caching to work?

### ISSUE THREAD

**Issue by cobrafast** [Antaris/RazorEngine#234]
I have implemented a custom TemplateManager like this:

	...
	public ITemplateSource Resolve(ITemplateKey key)
	{
		FileInfo fi = new FileInfo(this.tplpathprefix + key.Name);
		using (FileStream fs = fi.OpenRead())
		using (StreamReader r = new StreamReader(fs))
		{
			return new LoadedTemplateSource(r.ReadToEnd(), fi.FullName);
		}
	}
	...

Which works. Templates are loaded and executed - but they're not cached.  
The above code is executed every single time each template needs to be run (and from there I'd guess that it's recompiled too, because why else would it need the source code again).

I am settings my custom configuration like this:

	var cfg = new TemplateServiceConfiguration();
	cfg.Debug = false;
	cfg.Language = Language.CSharp;
	cfg.EncodedStringFactory = new RawStringFactory();
	cfg.TemplateManager = new Custom_TemplateManager();
	cfg.CachingProvider = new DefaultCachingProvider();
	cfg.CompilerServiceFactory = new DefaultCompilerServiceFactory();
	Engine.Razor = RazorEngineService.Create(cfg);

and then am using the `Engine.Razor.RunCompile` extension method like so:

	Engine.Razor.RunCompile(new NameOnlyTemplateKey(TemplateFileName, ResolveType.Global, null), typeof(MyModel), this);

Anything I'm doing wrong or is this a bug?

**Comment by matthid** [comment]
There are some things that can wrong, but your code looks good. Here are some hints:
- You are calling your configuration code only once?
- Do you have your own implementation of ITemplateKey? If yes you need to make sure to implement `Equals` and `GetHashcode`.

Besides that I don't know much that can go wrong, your code works for me. You are right, when the template is found in the cache `Resolve` should not get called.

**Comment by cobrafast** [comment]
Ah yes, I applied the configuration on every request.
I changed that and now caching seems to work! Thanks!
