### ISSUE TITLE
Is there a way to ignore exceptions when the model does not contain a definition for an model property?

### ISSUE THREAD

**Issue by mikeandersun** [Antaris/RazorEngine#236]
"Message":"An error has occurred.","ExceptionMessage":"'RazorEngine.Compilation.RazorDynamicObject' does not contain a definition for 'foo'".

**Comment by matthid** [comment]
Yes. It should work like this:
* Use `dynamic` (`modelType == null`).
* Use `RazorDynamicObject.Create(model, allowMissingMembers = true)` as your model.
