### ISSUE TITLE
RunCompile fails if there is no model but there is a ViewBag

### ISSUE THREAD

**Issue by PhilipDaniels** [Antaris/RazorEngine#237]
I have this line of code in my app

    dynamic vb = new DynamicViewBag();
    // add stuff to vb...
    razorEngineService.RunCompile(file.Contents, file.Filename, null, (DynamicViewBag)vb);

I call this when there is no @Model directive in the page. This used to work fine when vb was always null, but now I have started to create viewbags. The above line of code will fail when vb is non-null, with a RuntimeBinderException "Cannot perform runtime binding on a null reference".

It can be fixed by adding an (unused and pointless) "@model" directive to the cshtml file, or by injecting an empty model - this doesn't throw:

    var model = new object();
    razorEngineService.RunCompile(file.Contents, file.Filename, model.GetType(), model, (DynamicViewBag)vb);

but I don't think the first call should fail either. I have RazorEngine 3.5.2.

**Comment by matthid** [comment]
Your code looks strange. First you use the `DynamicViewBag` as your model:
```csharp
dynamic vb = new DynamicViewBag();

razorEngineService.RunCompile(file.Contents, file.Filename, null /*modeltype*/, (DynamicViewBag)vb /*model*/);
```

and then as your ViewBag
```csharp
var model = new object();
razorEngineService.RunCompile(file.Contents, file.Filename, model.GetType() /*modeltype*/, model /*model*/, (DynamicViewBag)vb /*viewbag*/);
```

I think what you want to do is this:

```csharp

dynamic vb = new DynamicViewBag();

razorEngineService.RunCompile(file.Contents, file.Filename, null /*modeltype*/, null /*model*/, (DynamicViewBag)vb /*viewbag*/);
```
(notice the additional `null`)

or this
```csharp
dynamic vb = new DynamicViewBag();

razorEngineService.RunCompile(file.Contents, file.Filename, viewBag = (DynamicViewBag)vb);
```

**Comment by PhilipDaniels** [comment]
You're right, I was calling the wrong overload, sorry. Adding the extra null fixed it.

Although it does bring to mind, if I am passing you the model instance why do I also have to pass the type? You could get it yourself in one line.

**Comment by matthid** [comment]
Because this way you can use the same compiled template for multiple types:
* You can either specify a base type (or interface)
* You can use dynamic (=null) for statically typed model instances.

Otherwise RazorEngine would force you to use the static type and re-compile the template again if you use other instances.

In short: You can strategically prevent unnecessary recompilations (which can save you several seconds in some situations).

Hope this makes more sense now :)

**Comment by matthid** [comment]
One more thing: I would like to add extra overloads without the modelType parameter and I agree that it would make sense. However there are already a lot of overloads available and adding these overloads would actually do more harm than good. I think a lot of calls would then be ambiguous and it would be impossible to figure out which overload you are calling.

**Comment by PhilipDaniels** [comment]
Oh believe me I agree, too many overloads are always confusing. Remove
rather than add :-) Maybe a fluent interface would be good

Compile(file.Contents).WithModel(myModel).WithViewBag(vb)


On 10 February 2015 at 13:25, matthid <notifications@github.com> wrote:

> One more thing: I would like to add extra overloads without the modelType
> parameter and I agree that it would make sense. However there are already a
> lot of overloads available and adding these overloads would actually do
> more harm than good. I think a lot of calls would then be ambiguous and it
> would be impossible to figure out which overload you are calling.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Antaris/RazorEngine/issues/237#issuecomment-73698190>.
>



-- 
Philip Daniels.
