### ISSUE TITLE
Referencing dynamic assemblies

### ISSUE THREAD

**Issue by BalassaMarton** [Antaris/RazorEngine#239]
Is there a way to reference a dynamic assembly? My solution generates the model type runtime. I've created a `IReferenceResolver` implementation which returns the assembly of the runtime generated type, but `RunCompile` throws `NotSupportedException`, even if Roslyn is used. From the stack trace, I can see that this isn't necessarily a RazorEngine issue, but still: how would you solve this problem?

**Comment by matthid** [comment]
If Roslyn doesn't even support it (maybe in the future they support it by compiling to a dynamic assembly), you can only fall back to a real assembly (AssemblyBuilder.Save)...

Ok there is probably one other way, can a dynamic assembly reference another dynamic assembly?
If the answer is yes, you could write your own CompilerService which compiles the given C# source code to a dynamic assembly, that would be an incredible improvement to RazorEngine (As we no longer would need Isolation for cleanup)!
Now with open-source Roslyn that task may not even be that difficult (but don't count on that).

**Comment by matthid** [comment]
I looked into this an tried out the CTP bits. While it was quite simple to adapt the current roslyn code to the old CTP API, the CTP sadly does not support `dynamic`... I ended my experiments right there. The best thing you can do is vote for them to add that feature back again: http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/6120992-support-for-collectible-assemblies

For anyone curious here is the code:  https://github.com/matthid/RazorEngine/tree/feature/collectible_assemblies

**Comment by BalassaMarton** [comment]
Hi, many thanks for your efforts!
For anyone interested, or hitting the same brick wall: I've come up with a solution. The problem was that Razor couldn't reference types in the dynamic assembly, even if it was saved to disk. My model types were generated by a factory object, which maps interfaces to generated classes, while assuring that the underlying class implements a set of other interfaces as well (the business layer only references the interfaces, the underlying type is irrelevant). The final (working) solution is this: the factory generates the types, saves the dynamic assembly to disk (the assembly has `Save` access only), then loads that assembly with `Assembly.Load`, and maps the types from the loaded (and hence fully functional, static) assembly.

**Comment by BalassaMarton** [comment]
Meh, now the template works perfectly, but the debugger throws internal errors, I suppose it's because of the types being loaded twice. Let's see what comes with MVC 6, and maybe I even dig into Roslyn and try to understand what it would take to make a compiler service that creates a dynamic assembly. That would be awesome.

**Comment by matthid** [comment]
I don't think this can be done anytime soon.
