### ISSUE TITLE
ResolveCSharpTypeName return invalid class name?

### ISSUE THREAD

**Issue by takepara** [Antaris/RazorEngine#240]
I call RunCompie with modelType are `System.Linq.Enumerable.WhereSelectEnumerableIterator<string>` .
But generated code inherits from `TemplateBase<System.Linq.WhereSelectEnumerableIterator<string>>` .

CSharpGetRawTypeName is greate generate type name. 
```
            return type.Namespace
                  + "."
                  + type.Name.Substring(0, type.Name.IndexOf('`'))
                  + "<"
                  + string.Join(", ", type.GetGenericArguments().Select(ResolveCSharpTypeName))
                  + ">";
```

```
            return type.FullName.Substring(0, type.FullName.IndexOf('`')).Replace("+", ".")
                  + "<"
                  + string.Join(", ", type.GetGenericArguments().Select(ResolveCSharpTypeName))
                  + ">";
```

How about this?

**Comment by matthid** [comment]
You are right there is a bug (I will release a fix soon).
However your code will not work anyway because `WhereSelectEnumerableIterator` is an internal class and therefore not accessible by the compiler (even after the type-name is correct). You need to use `typeof(IEnumerable<string>)` as your model type (which will work for the current version as well).

**Comment by takepara** [comment]
Thanks matthid.

I wrote LINQ result model set RunCompile.
And you are correct! WhereSelectEnumerableIterator is internal.
This is my my code sample.
```
IEnumerable<T> GetData(){  return list.Where(...).Select(...); }
```
But this result is WhereSelectEnumerableIterator instance...
I rewrite this code, with your advice!
```
IEnumerable<T> GetData(){  return list.Where(...).Select(...).ToArray(); }
```

**Comment by matthid** [comment]
ok 3.6.1 fixes the typename-generation bug.
BTW you don't need to change your `GetData` code:
```csharp
Engine.Razor.RunCompile(key,writer, typeof(IEnumerable<T>),data);
```
would also work.

**Comment by takepara** [comment]
Awesome!
Thank you, fast fixed and sample code.
