### ISSUE TITLE
Questions about temporary files

### ISSUE THREAD

**Issue by xpicio** [Antaris/RazorEngine#260]
Hello, i'm using RazorEngine 3.6.3 in a mvc 5 application and on asp. net 4.5 webform application in both cases to build a template for email notifications.

Sometimes this error occurs:

Errors while compiling a Template.
Please try the following to solve the situation:
  * If the problem is about missing references either try to load the missing references manually (in the compiling appdomain!) or
    Specify your references manually by providing your own IReferenceResolver implementation.
    Currently all references have to be available as files!
  * If you get 'class' does not contain a definition for 'member': 
        try another modelType (for example 'null' or 'typeof(DynamicObject)' to make the model dynamic).
        NOTE: You CANNOT use typeof(dynamic)!
    Or try to use static instead of anonymous/dynamic types.
More details about the error:
 * error: (0, 0) Impossibile scrivere nel file di output 'c:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\RazorEngine_gvxrryft.gbb\CompiledRazorTemplates.Dynamic.RazorEngine_03fe56d0d56d4499a85a1f3caa205d9b.dll': 'Disponibilità insufficiente per completare il servizio richiesto. '
Temporary files of the compilation can be found in (please delete the folder): C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\RazorEngine_gvxrryft.gbb
The template we tried to compile is: ....

Checking the folder _C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp_ i have seen that there are more than 80.000 RazorEngine temporary folders, and are increasing. In _C:\Windows\Temp_ the are about 20 folders, as many templates in my applications.

1. Is it safe delete these folders when the applications are running ?
2. When a temporary file is created ? 
3. Register the ```IRazorEngineService```instance as singleton in a DI context will reduce the number of temporary files created (at the moment i'm using a new instance for each template, the refactoring to a single instance is in progress) ?
4. Why RazorEngine folders are created in _C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp_ and in _C:\Windows\Temp_ ?

**Comment by matthid** [comment]
First of all: You should update to the latest version. The latest version improves the deletion process.


> * Is it safe delete these folders when the applications are running ?

Yes, as long as you do not delete locked files you are fine.

> * When a temporary file is created ?

Yes, as long as you do not delete locked files you are fine. You could get invalid error messages which contain references to non-existent files. Actually all those non-locked files are deleted fine (even in older version). So this approach doesn't make a lot of sense.

> * Register the IRazorEngineService instance as singleton in a DI context will reduce the number of temporary files created (at the moment i'm using a new instance for each template, the refactoring to a single instance is in progress) ?

Sure if you create new IRazorEngineService instances all templates need to be compiled again.
Note that you can also share a global ICachingProvider, but that might get tricky if you use different resolving strategies.

> * Why RazorEngine folders are created in C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp and in C:\Windows\Temp ?

We use the current users temp directory, so the exact location depends on the user running the RazorEngine code.

**Comment by xpicio** [comment]
Thanks for the info.
