### ISSUE TITLE
[3.6.4] DisableTempFileLocking = true still spams the console with warnings

### ISSUE THREAD

**Issue by Cherepoc** [Antaris/RazorEngine#263]
Hello!
I have a console application that uses razorengine. After latest updates I desided to use DisableTempFileLocking - it fits my needs perfectly. I thought enabling it will make the stderr warning about temporary files go away, but it didn't. Is there a way to disable this behavior?
Thanks!

**Comment by matthid** [comment]
Sure, use `config.CachingProvider = new DefaultCachingProvider(t => {})`, which basically says to the caching provider to not care about cleanup. You can use this callback in the `DisableTempFileLocking = false` case to handle the cleanup logic yourself.
It is (sparsely) documented here: http://antaris.github.io/RazorEngine/#Temporary-files

**Comment by Cherepoc** [comment]
Thanks, missed it in the documentation somehow
