### ISSUE TITLE
Ability to test for undefined property on a dynamic model.

### ISSUE THREAD

**Issue by robmen** [Antaris/RazorEngine#264]
I have templates that take *very* dynamic models. For example, I often find myself want to do something like:

    <div>
    @if (Model.Foo.Link != null) {
      <a href="@Model.Foo.Link">@Model.Foo.Text</a>
    }
    else {
      <p>@Model.Foo.Text</p>
    }
    </div>

Where `Foo` is 100% `dynamic` and may or may not have had a `Link` string property assigned to it.

Now, I have enabled `AllowMissingPropertiesOnDynamic`, like so:

    var config = new TemplateServiceConfiguration();
    config.AllowMissingPropertiesOnDynamic = true;
    config.Namespaces.Add("System.IO");
    config.Namespaces.Add("RazorEngine.Text");

And simply referencing an absent dynamic property does seem to result to "empty". For example: `<a href='@Model.Foo.Link'>` will leave the `href` empty. However, testing for the missing property (like above) will throw an exception (I don't have it in front of me but I can get it if desired).

I wandered through the RazorEngine code for a while and it seems an `object` is being newed up for missing properties when `AllowMissingPropertiesOnDynamic` is `true`. I had the thought that if that object was static, it could maybe be compared against. Maybe something like any of the following:

    @if (Model.Foo.Link == Razor.Undefined)
    @if (Model.Foo.Link == Undefined())
    @if (Undefined(Model.Foo.Link))

Anyway, you'll know better than I what might work. I just hope there is something that could be added. Thanks.

PS: it's totally possible I've missed a mechanism to accomplish testing for an undefined property in a template. If so, I'd really appreciate a pointer to it and I'll happily go read. :sweat_smile:

**Comment by matthid** [comment]
There currently is no way to do this as long as `AllowMissingPropertiesOnDynamic` is `true` if you are fine with that you can check against an empty string:

```csharp
@if (!string.IsNullOrEmpty((string)Model.Foo.Link)) {
```

if you are not sure if `Link` can be casted to to `string` you can use:
```csharp
@if (!string.IsNullOrEmpty(Model.Foo.Link.ToString())) {
```
Which should almost always work.

On the other hand you can set `AllowMissingPropertiesOnDynamic` back to `false` and do it the same way you would do it in C#:

```csharp
@try {
  // save all properties which might be missing beforehand in variables (otherwise there will be partial ouput).
  var link = Model.Foo.Link; 
  // Use them as you would normally.
  <a href=""@link"">@Model.Foo.Text</a>
}
catch (RuntimeBinderException) {
  <p>@Model.Foo.Text</p>
}
```

**Comment by matthid** [comment]
Closing this as I assume one of the suggested options did fit your needs?
