### ISSUE TITLE
Programmatically accessing sections

### ISSUE THREAD

**Issue by impworks** [Antaris/RazorEngine#266]
Is it possible to extract section content programmatically using RazorEngine?

    // template file
    @section Header {
        <text>Hello from @Model.Name</text>
    }
    @section Body {
        <div>@Model.Content</div>
    }

**Comment by matthid** [comment]
Do you want the section template content "`<text>Hello from @Model.Name</text>`" or the section output "`Hello from myname`"? And may I ask why?

**Comment by impworks** [comment]
I want to use Razor for email templates. It would be very convenient to store the email title alongside its body and use it like this (with hypothetical method names):

    void SendEmail<T>(string recepient, string templatePath, T model)
    {
        using(var reader = new StreamReader(templatePath))
        {
            var compiled = Engine.Razor.Compile(reader.ReadToEnd(), typeof(T), model);
    
            SendMail(
                recepient: recepient,
                title: compiled.GetSectionOutput("title"),
                body: compiled.GetSectionOutput("body")
            );
        }
    }

**Comment by matthid** [comment]
Ah I saw people doing this before, please see #225 and #238. I think they may contain the solution you are looking for.

**Comment by impworks** [comment]
Thanks, I'll give it a go!
