### ISSUE TITLE
Unable to move to new syntax

### ISSUE THREAD

**Issue by dathayer23** [Antaris/RazorEngine#282]
Changed form Razor to Engine.Razor after getting multiple errors found entry in your blog indicating I need to reference Razor.Templating.  Did that it didn't work.  Reverting to old syntax.  Suggest before removing old syntax you create mainline functionality that does not break existing code or modify your extensions so that they actually compile when referenced from code.  This kind of adhoc inconsistency is what gives open source a bad name.

**Comment by matthid** [comment]
I'm not sure if I understand what you are saying, could you maybe give an example of what's not working?
You cannot just replace Razor with Engine.Razor. The API is completely new and build from scratch, that's the reason why the old API is still there (for backwards compat). I do not plan to make the new API backwards compatible (I rather just keep the old one for some time)...

**Comment by rustybox** [comment]
Could do with updating the docs

    string template = "Hello @Model.Name, welcome to RazorEngine!";
    var result =  Engine.Razor.RunCompile(template, "templateKey", null, new { Name = "World" });
    // Argument 1: cannot convert from 'string' to 'RazorEngine.Templating.ITemplateKey'
