### ISSUE TITLE
Performance issues when Compiling in a VSPackage/Visual Studio Extension

### ISSUE THREAD

**Issue by EvdHeide** [Antaris/RazorEngine#286]
Hi,
Thank you for developing RazorEngine, we've been using it successfully in a standalone application.
However, we want to use it inside a VSPackage (Visual Studio Extension). We use the exact same code we've been using in our standalone application and it works, but the performance is horrible. 

It takes exactly 30 seconds every time we compile a template, since we will be using a lot of templates this quickly adds up to a very long time. Because it takes exactly 30 seconds every time, we have a feeling it might have something to do with the RazorEngine trying to do something and then giving up after a timeout (Maybe trying to cache something?). 

No exceptions are thrown and the template is successfully compiled.

We use the following code:
for setup:

	var config = new TemplateServiceConfiguration();
	config.Language = Language.CSharp;
	config.EncodedStringFactory = new RawStringFactory();

	\\We also tried it with the following two lines enabled
	\\config.CachingProvider = new DefaultCachingProvider(t => { });
	\\config.DisableTempFileLocking = true;

	var service = RazorEngineService.Create(config);
	Engine.Razor = service;

And for actually compiling:

	Engine.Razor.AddTemplate(cacheName, new LoadedTemplateSource(data, cacheName));
	Engine.Razor.Compile(cacheName, typeof(RazorModel));

Is this a known issue and if so, does anyone know how to resolve this?

Thanks in advance.

**Comment by matthid** [comment]
If you already tried with the cleanup logic disabled and in-memory templates I can only assume its because of the CodeDom compiler? Can you maybe try out the Roslyn Compiler (RazorEngine.Roslyn nuget package)?

Is the template properly cached (and fast the second time it's used?)?
Default caching is in-memory only so I'm not sure why it should take 30 seconds...

Can you get a stacktrace where the program is within the wait time? Did you try profiling?

Hope this provides some points to further track this down...

**Comment by coxp** [comment]
I think this issue was previously caused by RazorEngine trying to reference
all the assemblies that VS also referenced while compiling the template.

I think you can now create a custom assembly resolver to restrict the
assemblies that are referenced and this should bring the compile time down.

**Comment by EvdHeide** [comment]
Thank you both for the quick reply.
Loading the required assemblies as proposed by coxp solved our problems.
This brought the compile time down to under a second per template.
