### ISSUE TITLE
LINQ Extension methods not available to use in templates

### ISSUE THREAD

**Issue by dankarmy** [Antaris/RazorEngine#287]
I'm in the process of upgrading from 3.5 to 3.7 and hit an issue with referencing extension methods in System.Linq namespace.

My template looks like this:

@using System.Linq;
@{
        var test = Model.Data.FirstOrDefault();
}
@test

Model.Data is as HashSet<string>.

RunCompile throws an exception:

An unhandled exception of type 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' occurred in System.Core.dll

Additional information: 'System.Collections.Generic.HashSet<string>' does not contain a definition for 'FirstOrDefault'

I presume there was some kind of change from 3.5 -> 3.7 as all my current templates that work in 3.5 do not work in 3.7 due to a call to various FirstOrDefault/First methods.

Is there a way to resolve this issue?

**Comment by dankarmy** [comment]
Forgot to mention that I've played with a custom reference resolver, but I don't understand why the default "UseCurrentAssembliesReferenceResolver" isn't sufficient.

**Comment by matthid** [comment]
Can you show your "Compile" or "RunCompile" call? I guess you are using `dynamic` instead of a static type, that's probably the reason why it won't work... Use `typeof(MyModel)` instead of `null` for the `modelType` argument.

**Comment by aviatrix** [comment]
I've just experienced the same issue, after i upgraded to 3.7 this started popping up 

however my T isn't dynamic ```where T : ModelBase```
```RazorInstance.Instance.RunCompile(viewKey, tw, typeof(T), page, viewbag);```
I have other instances where The type is dynamic, and there were no issues too.

**Comment by matthid** [comment]
@aviatrix  Can you provide a self contained sample?

**Comment by aviatrix** [comment]
I will try to replicate it and send you the sample

**Comment by aviatrix** [comment]
@matthid just before i sent you a repo with the code i realized what was my mistake.
i had ```@model dynamic``` appended to my views, when removed, it worked like a charm for concrete types, except for ```ExpandoObject```

https://github.com/aviatrix/RazorEngineTest

However this was not the case prior to 3.5 
Any ideas?

**Comment by aviatrix** [comment]
@matthid  ping?

**Comment by matthid** [comment]
@aviatrix Well, your scenario sounds like a bug in pre 3.5 which has been fixed. ExpandoObject is a known quirk (it will be considered as "dynamic"). Does this help?

**Comment by aviatrix** [comment]
@matthid Yeah, makes sense, however i can't seem to get to work linq with ExpandoObject, which is what i currently want to do, so something like in the example repo ( `@Model.StringField.Take(5)` ) doesn't blow up.

**Comment by matthid** [comment]
You need to either cast or save it to a statically typed variable
```
@{
string[] fields = Model.StringField;
}
...
@fields.Take(5)
```

Or use the method explicitly:
`@System.Linq.Enumerable.Take(Model.StringField, 5)`


or don't use ExpandoObject at all and use a statically typed class instead.
Whatever you prefer.

Note I don't think this is supported at all in Razor MVC.
