### ISSUE TITLE
Setting DisableTempFileLocking = true does not stop the console messages

### ISSUE THREAD

**Issue by mondss** [Antaris/RazorEngine#288]
Having DisableTempFileLocking = true doesn't seem to stop the messages about temporary files coming through to the console. This is the configuration I am using:

    IRazorEngineService razorService = RazorEngineService.Create(new TemplateServiceConfiguration
                {
                    DisableTempFileLocking = false
                });

    Engine.Razor = razorService;

**Comment by matthid** [comment]
The documentation reads "To remove the RazorEngine warnings you can additionally use config.CachingProvider = new DefaultCachingProvider(t => {})". You basically removed the file leakage but out detection and cleanup logic is still in place.

**Comment by mondss** [comment]
Thanks :>

**Comment by anritter** [comment]
<configSections>
    <section name="razorEngine" type="RazorEngine.Configuration.RazorEngineConfigurationSection, RazorEngine" requirePermission="false" />
  </configSections>  
<razorEngine disableTempFileLocking="true"></razorEngine>
