### ISSUE TITLE
Can no longer set a default Layout (3.4 to 3.7 upgrade)

### ISSUE THREAD

**Issue by antscode** [Antaris/RazorEngine#289]
Hi there,

Firstly thanks for this excellent project. In 3.4 we could define a default layout like this:

    var template = _templateService.Resolve(templateName, model);

    var templateBase = template as TemplateBase;
    templateBase.Layout = layoutName;

    return template.Run(new ExecuteContext());

But since moving to 3.7, there appear to be no methods that return an ITemplate - and as such we cannot specify the default layout. e.g.: now we can only do this:

    _templateService.RunCompile(templateName, GetModelType(model), model);

i.e the methods *AddTemplate*, *Compile* and *RunCompile* all return void - hence no ability to access the underlying template.

I understand we could rectify this by specifying a Layout within the views themselves, however we already have hundreds of existing templates that don't have this.

Any suggestions on how we could overcome this?

Many thanks,
Anthony.

**Comment by matthid** [comment]
Yes, you can try to use a custom TemplateBase class for this.

Something along those lines (written with notepad, so might not compile):

    public class TemplateBaseWithDefaultLayout : TemplateBase {
        public TemplateBaseWithDefaultLayout() {
            this.Layout = "Default";
        }
    }

    config.BaseTemplateType = typeof(TemplateBaseWithDefaultLayout);

Now you can just use the `Compile`+`Run` and `RunCompile` methods as usual.

Does this solve your problem?

**Comment by antscode** [comment]
Thanks so much for your reply. Yes I had already tried this as we already have a custom TemplateBase - however it results in a StackOverflow exception and kills the thread in IIS!

But if this is the recommended approach, then I'll download the source code and try and figure out why this results in an overflow.

I'll send you an update once I've given it a go.

Cheers,
Anthony.

**Comment by matthid** [comment]
Ah yes because it possibly tries to apply the layout to the layout itself, currently I'm a bit time limited. So if you can come up with a solution yourself I would gladly accept a pull request, otherwise you need to wait some time until I can look into it. Just use the legacy API in the mean time...

**Comment by matthid** [comment]
Another workaround for now would be to override `SetData` and set the layout from a `viewbag` property, and override `ResolveLayout` to copy the `viewbag` and remove the layout before resolving the layout.

**Comment by antscode** [comment]
THANK YOU. I was able to resolve the problem based on your suggestion, this is the overridden SetData method in our TemplateBase class:

    public override void SetData(object model, DynamicViewBag viewbag)
    {
        var data = (dynamic)viewbag;

        if (data != null)
        {
            this.Layout = (string)data.Layout;

            // We clear the layout once set in the top-level template
            // to prevent the layouts from referencing themselves / infinite loop
            data.Layout = null;
        }

        base.SetData(model, viewbag);
    }

Then we specify the template before compiling like this:

    var data = new DynamicViewBag();
    data.AddValue("Layout", "Layouts/SiteLayout.cshtml");

    return _templateService.RunCompile(templateName, GetModelType(model), model, data);

Cheers,
Anthony.

**Comment by matthid** [comment]
Nice, thanks for posting a working solution! Just for completeness sake, if something stumbles across this, I think this (or something like it) should work without viewbag:

    public class TemplateBaseWithDefaultLayout<T> : TemplateBase<T> {
        public TemplateBaseWithDefaultLayout() {
            this.Layout = "Default";
        }
        
        override ITemplate ResolveLayout(string name)
        {
            var b = (TemplateBaseWithDefaultLayout)base.ResolveLayout(name);
            b.Layout = null;
            return b;
        }
    }

    config.BaseTemplateType = typeof(TemplateBaseWithDefaultLayout);
