### ISSUE TITLE
How to include Viewbag in included template

### ISSUE THREAD

**Issue by trankdog** [Antaris/RazorEngine#291]
@Include("templateName", model = null, modeType = null) to include another template.

Is there a way to pass a new ViewBag to the included template, similar to how PartialViews allow passing of new ViewBags? Basically I'd just like a way to dynamically set if the PartialView should use a layout page without setting it in the model. Also, there's a spelling error in the documentation, should be

@Include("templateName", model = null, modelType = null) to include another template.

**Comment by matthid** [comment]
No this is currently not possible. Is this request related to #289. Or how do you set the layout from tie viewbag?
