### ISSUE TITLE
Strange CPU spikes - Hard to track down actual cause

### ISSUE THREAD

**Issue by ChrisDerrig** [Antaris/RazorEngine#292]
Hello,

We recently went live with some email templates using RazorEngine to generate them, and that seems to be fine.  However the problem we're getting is that with these templates, the CPU on the server will randomly spike to 100% and essentially freeze everyone out.  The bigger puzzle on this seems to be that this tends to happen if users access it via the alias for the site, rather than the fully qualified domain name.  The memory on the servers is fine, never has issues, it's really the CPU that goes crazy.

We're using 3.7.0 (the latest available in Nuget), and we've tried a ton of different implementations to try and get this working, our latest is the one that has the above mentioned strange behavior with the alias killing it, but the fqdn being fine.

Among things we've tried:
- Setting DisableTempFileLocking  = false and setting the call back on the Default Cache Provider to t=> {}.
- Creating a template manager and configuring the service only once at Application_Start(), compiling the templates there, and then just using .Run when they are needed.  (It should be noted that this would have caused other issues, since we also generate these emails from a scheduled EXE using the same domain layer, but we probably could have just popped the code from application_start into the main)
- Tried using the IsolationRazorEngineService but our model that we're using has reliance on some Entities and to make them serializable might cause more issues elsewhere, even tried it using RazorDynamicObject.Create(model) but that started throwing even more errors and never made it past my local onto a server.

We're also able to reproduce this in our dev and uat environments if at least 3 users start hitting the site (and the pages where we process the emails).  I'm not sure if it's just trying to compile the templates and that is causing the huge CPU spike, or why it's only happening on the aliases but not on the fqdn (I'm not convinced it's Razor's fault since it will happen before we ever get to an email generating page, but when we commented out the Razor email code, we can no longer reproduce it, no matter how many users we put)

Have you seen any other instances of the CPU spiking like this?  The production and UAT webservers are both load-balanced, and it seems to happen no matter which server gets hit.

The code as we have it right now is as follows:
```C#
        public string GetEmailContent(string templateContent)
        {
            
 var config = new TemplateServiceConfiguration();
       config.CachingProvider = new DefaultCachingProvider(t => { });            
       var service = RazorEngineService.Create(config);
       var emailHtmlBody = service.RunCompile(templateContent, "EmailTemplate_" + _languageType, typeof(EmailVM), GetViewModel());

            config.CachingProvider.Dispose();
            service.Dispose();
 return emailHtmlBody;

        }
```

but obviously this has the drawback of creating a new service each time we get the email content, which probably isn't helping our performance issue, however it still seems to be faster than using a template manager in Application_Start().

Like I mentioned, if we comment out this code, then the website seems to be fine everywhere, but if we leave it (even if it shouldn't be being called?) the CPU jumps.  I'm pretty much out of ideas and now my lead is talking about pulling the plug on using RazorEngine on the website side and just using the System.Web.Razor, which would give us 2 implementations for generating the same email templates, as well as requiring a refactoring of our domain layer which i'd like to avoid.  Any help is appreciated at this point!

Thank you

**Comment by matthid** [comment]
Just pointing out the obvious in your code: You definitely need to cache the `service` or `CachingProvider` (part of `service`) instance across the `GetEmailContent` calls. Otherwise you are re-compiling the template on each call, which one expects to be slow.

**Comment by ChrisDerrig** [comment]
Yeah, this implementation was mostly because it was the one that seemed to
work with the least issues. The weird part is that the CPU hits 100%
though, and not necessarily when calling this code, but if we comment out
this code, the 100% spike disappears.

**Comment by matthid** [comment]
Well, you already disabled the only "behind the scenes" magic that comes to mind for weird behavior with `new DefaultCachingProvider(t => { });`. 

So you need to profile those spikes. It could be anything including unrelated stuff in your configuration to the GC. 

> The weird part is that the CPU hits 100% though, and not necessarily when calling this code

I'm not aware of any RazorEngine component that causes CPU usage in the background (with the exception of the cleanup code you already disabled).

Please either try to reproduce it in a console application or try to profile it (or send a stacktrace from such a spike)

**Comment by ChrisDerrig** [comment]
In the end my Team lead forced me to remove it, at least from the web side.  In a Console app, everything works fine, but in an MVC Web app (using the same service layer), the CPU would randomly spike and not come down.  Unfortunate I cannot get any of the system logs/profiles since it is the server team that handles that part and they don't want to give us anything.  

I still have the reference in the same service layer, but now the web calls one function (using the basic System.Web.Razor), and the console app calls a second one using RazorEngine, and everything works just fine, even under load.

**Comment by matthid** [comment]
Ok I'm closing this for now, please comment if there is more info.
