### ISSUE TITLE
Support role/claim-based link rendering in ASP.NET MVC applications

### ISSUE THREAD

**Issue by hurtonypeter** [Antaris/RazorEngine#294]
In many cases we would not like to render links which points to an action that would drop HTTP403 for the user. Sometimes it is enough to override the Html.ActionLink() function, but if we use for example icons in link, than we need to write down the 'a' tag, and generate the href with Url.Action().
With this the best you could do is return an empty string with Url.Action, but it is also not on option, because it will render a link - a broken link.

My goal would be that somehow the Razor parser would check the link's target, and if it is a forbidden action, it hides the link completely.
For example there is a controller:
```
public class MyController : Controller
{
   [Authorize(Roles = "Admin")]
   public ActionResult Index() {}
}
```
And a link in a cshtml file:
```
<a href="@Url.Action("Index", "My")"><span class="icon"></span> link to somewhere</a> 
```

If the user is not in the Admin role, this link should not rendered into the response.

How could I achieve this behaviour? Can I override the parser to handle this? Thanks a lot!

**Comment by matthid** [comment]
This repository is not related to ASP.Net. And we don't override the parser in any way (we just use it).
Please take a look at: https://github.com/aspnet/Mvc and https://github.com/aspnet/Razor/

Just one hint, which is not what you asked for but may help you:
In RazorEngine you can extend the Razor Syntax by providing your own Template base class.
https://antaris.github.io/RazorEngine/TemplateBasics.html#Extending-the-template-Syntax
Something similar might be possible in the ASP.net world and it might be exactly what you are searching for.
