### ISSUE TITLE
Model not recognized

### ISSUE THREAD

**Issue by nojaf** [Antaris/RazorEngine#295]
Hi,

This isn't really a question regarding the project but I'm guessing you guys can help me out.
I'm trying to setup a class library with Views and RazorEngine.
It all works out but I'm not receiving intellisense for @Model directive.
```razor
@model MyFullNameSpace.Model 
```
get's accepted but 

```razor
<p>@Model.Property</p>
```
 doesn't complete any of the properties.

I've followed https://conficient.wordpress.com/2013/11/27/asp-net-razor-views-in-class-libraries/ and copied the web.config of an existing mvc project in the same solution (one I wish to remove in the future).

Compiling and using the template all works fine but it's a pain not having the code completion.
Does anyone have any idea for this tooling question?

Thanks,
nojaf

**Comment by nojaf** [comment]
Ok I just visited https://antaris.github.io/RazorEngine/IntellisenseAndResharper.html
And what's described isn't working out.

```
@inherits RazorEngine.Templating.TemplateBase<MyViewModel>
```

is getting a not found error. I'm using VS 2015 RC with ReSharper

**Comment by matthid** [comment]
> Your project output path is set to `bin\` instead of `bin\Debug\` and `bin\Release\`.

Did you do this and then re-compile your project?

**Comment by nojaf** [comment]
Yeah did work out, ended up creating a class that extends HtmlTemplateBase<T>.
I get my intellisense now but VS is complaining about the @inherits statement.
RazorEngine should be reference to the project. Which it obviously is but yeah ...

**Comment by matthid** [comment]
Just make sure all required references are in the `bin\` folder and are up2date. The problem is that this is no native RazorEngine support, instead we re-use the MVC Intellisense which is a bit cumbersome. Let me know if there are still problems.

**Comment by nojaf** [comment]
My bin folder wasn't located in the project folder. I changed that and all looks good now.
Thanks for the help
