### ISSUE TITLE
Dynamic.RazorEngine_ cannot be used for return type 'RazorEngine.Templating.ITemplate'

### ISSUE THREAD

**Issue by mohsinali1317** [Antaris/RazorEngine#297]
I am using RazorEngine to compile my .cshtml file (having partial views in it). I am getting this error
**Dynamic.RazorEngine_ cannot be used for return type 'RazorEngine.Templating.ITemplate**. My code looks like this

    var config = new TemplateServiceConfiguration();
    config.Namespaces.Add("TippNett.Resources");
    config.Namespaces.Add("TippNett.Core");

    config.BaseTemplateType = typeof(System.Web.WebPages.WebPageBase); // this line causes the above error
    
    var service = RazorEngineService.Create(config);

**Comment by matthid** [comment]
You need to use a implementation of `ITemplate` as `BaseTemplateType`. RazorEngine is not related to System.Web and doesn't depend on it.
If you need to create a custom base class you can use `TemplateBase<'T>` to simplify the implementation work.

But it's not clear to me what you are trying to achieve. More details can be found here: https://antaris.github.io/RazorEngine/TemplateBasics.html

**Comment by mohsinali1317** [comment]
My cshtml view has 

    @RenderPage("~/Views/Home/subPagesForApp/_reportAbuse.cshtml")
    @Html.Raw("test")
    // the above two are working, but I am having issues with the last one. Can you help me putting the required function for Html.Partial? 
    @Html.Partial("~/Views/Home/subPagesForApp/_singleLocationWindow.cshtml")

My custom template base is like this

    public class MyHtmlHelper
    {
        public IEncodedString Raw(string rawString)
        {
            return new RawString(rawString);
        }
    }

    public abstract class MyCustomTemplateBase<T> : TemplateBase<T>
    {
        public MyHtmlHelper Html { get {return new MyHtmlHelper(); } }

     public HelperResult RenderPage(string path, params object[] data)
        {

            string template = File.ReadAllText(cpp.GetFile(path).VirtualPath);

            HelperResult hr = new HelperResult((tw) =>
             {
                 tw.Write(template);
             });

            return hr;
        }
        }
    }
