### ISSUE TITLE
Having hard time clearing template cache

### ISSUE THREAD

**Issue by gsogol** [Antaris/RazorEngine#298]
I've seen a different thread about difficulties in cache invalidation butI feel like this should be designed differently where cache invalidation should happen easily. If CLR is the problem then may be the way RazorEngine is designed should be done differently. I see a lot of people asking the same question over and over again.

My issue, my original code was:
<code>

            Engine.Razor.AddTemplate("~/templates/_layout", File.ReadAllText("_Layout.cshtml"));
            Engine.Razor.Compile("~/templates/_layout", null);
            Engine.Razor.AddTemplate("~/templates/postfinished", File.ReadAllText("PostFinished.cshtml"));
            Engine.Razor.Compile("~/templates/postfinished", null);
            dynamic model = new ExpandoObject();
            model.FirstName = "Name";
            var text = Engine.Razor.Run("~/templates/postfinished", null, (object)model);
</code>

I then realized that <code>"~/templates/...."</code> made no sense and corrected to simple strings but every time I run I get " System.ArgumentException: Please either set a template manager to resolve templates or add the template '~/templates/_ayout.cshtml'! at RazorEngine.Templating.DelegateTemplateManager"

I rerun the code above with new keys like "key1" and I Still get the message above. I restarted my azure webjob and I get the message above. How do I get rid of it? I made a mistake naming a key and now get punished for it. How come restarting the process the whole azure webjob project does not clear the cache? I at least want to manually clear the cache.

Please help out.

**Comment by matthid** [comment]
> If CLR is the problem then may be the way RazorEngine is designed should be done differently. 

Do you have a suggestion? Hiding memory leaks by default just because people complain is not an option IMHO (RazorEngine already provides the implementations for it if you want to do it).

>  " System.ArgumentException: Please either set a template manager to resolve templates or add the template '~/templates/_ayout.cshtml'! at RazorEngine.Templating.DelegateTemplateManager"

This error message is not related to the caching problem. I would guess (through psychic debugging) that you have a typo in your code:

```csharp
Engine.Razor.AddTemplate("~/templates/_layout", File.ReadAllText("_Layout.cshtml"));
Engine.Razor.Compile("~/templates/_ayout", null); // Will throw because of missing "l"
```

The strings need to match for RazorEngine to be able to find the template.

By the way nothing is persistent, so a restart of the webjob should definitely clear all caching errors.

Hope this helps, feel free to ask further question if I should re-open.

**Comment by gsogol** [comment]
I just pasted it wrong, not a typo. all keys match in code. Restart the job, same error message every time. Not sure what else to do here.

**Comment by matthid** [comment]
Can you share the complete code or a repro?

**Comment by gsogol** [comment]
Dang it, the cshtml file was pointing to the wrong location. the keys were right but the reference to the layour still had the wrong location. Azure WebJobs cannot have subdirectories and need those cshtml files at the root (AFAIK). Sorry and thank you for helping

**Comment by gsogol** [comment]
Pulled the trigger a little too fast.

I have the following:
<code>
            Engine.Razor.AddTemplate("_layout", File.ReadAllText("_Layout.cshtml"));
            Engine.Razor.Compile("_layout", null);
            Engine.Razor.AddTemplate("postfinished", File.ReadAllText("PostFinished.cshtml"));
            Engine.Razor.Compile("postfinished", null);
</code>

My template:
<code>
@model dynamic
@{
    Layout = "_Layout.cshtml";
}
<h1>Hello @Model.FirstName</h1>
</code>

Get the following now "System.ArgumentException: Please either set a template manager to resolve templates or add the template '_Layout.cshtml'! at RazorEngine.Templating.DelegateTemplateManager.<.ctor>"

**Comment by gsogol** [comment]
It seems to work if the key is the name of the cshtml file. The documentations talks about setting any key. It works now but only if the key is the same as the template file name

**Comment by matthid** [comment]
Yes the keys need to match
```csharp
Engine.Razor.AddTemplate("KEY", File.ReadAllText("_Layout.cshtml"));
Engine.Razor.Compile("KEY", null);
//...
@model dynamic @{ Layout = "KEY"; } Hello @Model.FirstName 
```

So in your situation you could either change the template 

```csharp
@model dynamic @{ Layout = "_layout"; } Hello @Model.FirstName
```

or your code (as you already noticed).

The key can be any string, they just need to match

**Comment by gsogol** [comment]
Got it. Thanks again
