### ISSUE TITLE
Simple example from docs not working

### ISSUE THREAD

**Issue by stephenpanzer** [Antaris/RazorEngine#300]
The first example in the documentation is failing for me:

    // using RazorEngine.Templating; // Dont forget to include this.
    string template = "Hello @Model.Name, welcome to RazorEngine!";
    var result =
        Engine.Razor.RunCompile(template, "templateKey", null, new { Name = "World" });

With the error:

    A first chance exception of type 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' occurred in Microsoft.CSharp.dll

    Additional information: 'RazorEngine.Compilation.RazorDynamicObject' does not contain a definition for 'Name'

Now, I see a lot of people complaining about various RuntimeBinderExceptions when using anonymous types, but no good explanation why the documentation seems to differ so much from reality. Are anonymous types actually supported? Is there some extension method I'm missing (I've included RazorEngine.Templating)?

RazorEngine version 3.7.0, .NET 4.5

**Comment by matthid** [comment]
Any more details about your environment? A simple console application with just RazorEngine? Obviously this worked the last time I tried, and actually all the examples are part of the unit test suite and the example application.

**Comment by stephenpanzer** [comment]
Yup, simple console app. Happens w/ both debug and release builds.
It appears to be an issue with my solution file - creating a new solution and installing RazorEngine seems to bypass any problems. What are some things that could be wrong with the solution?

Full code:

    using System;
    using RazorEngine;
    using RazorEngine.Templating;

    namespace TestApp
    {
        class Program
        {
            //First argument is email template name, second argument is client ID
            static void Main(string[] args)
            {
                // using RazorEngine.Templating; // Dont forget to include this.
                string template = "Hello @Model.Name, welcome to RazorEngine!";
                var result =
                    Engine.Razor.RunCompile(template, "templateKey", null, new { Name = "World" });
            }
        }
    }

**Comment by matthid** [comment]
Can you zip up the problematic solution and provide it here (or send it to me directly)?

**Comment by stephenpanzer** [comment]
I'll see what I can do to try and isolate the problem - I'm not going to be able to send the whole solution because it contains company code.

**Comment by matthid** [comment]
Ok, looking forward to that. Currently I have no idea what might be causing this.

**Comment by matthid** [comment]
Maybe a problem with the project (.csproj) configuration

**Comment by matthid** [comment]
Closed due to inactivity, feel free to comment with some additional information.

**Comment by houseme-brandon** [comment]
I am experiencing this bug too.. it is strange that it is throwing that exception because if I ignore the exception then it will compile the template. It would be nice for this to not throw an exception.. Any ideas as to why? Was it reproducible from the above console app?
