### ISSUE TITLE
Basic example throws an exception for ASP.NET 5 project

### ISSUE THREAD

**Issue by korzh** [Antaris/RazorEngine#301]
I've tried to run the very first example using version 4.2.0-beta in ASP.NET 5 (MVC 6.0) project and got the following error message:

> Could not load type 'Microsoft.AspNet.Razor.Text.SourceLocation' from assembly 'Microsoft.AspNet.Razor, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'.
>    at RazorEngine.Compilation.RazorEngineHost.DecorateCodeParser(ParserBase incomingCodeParser)
> .   .   .   .   .   .

**Comment by matthid** [comment]
Did you use the beta nuget packge?

**Comment by korzh** [comment]
Yes. The latest available one: 4.2.0-beta2

**Comment by matthid** [comment]
I have no Idea when I can look into this (And update RazorEngine), but I guess it has to do with the fact that you are using another version then the one RazorEngine has been compiled with...

**Comment by korzh** [comment]
And the version RazorEngine was compiled with is...?

**Comment by matthid** [comment]
4.0.0-beta1, see https://github.com/Antaris/RazorEngine/blob/master/src/nugetDependencies/razor4/packages.config

**Comment by korzh** [comment]
I've tried to compile RazorEngine with version 4.0.0-beta5 of Microsoft.AspNet.Razor but got the same error.
What I did:
 * Downloaded RazorEngine sources from master branch
 * Changed the version of reference Microsoft.AspNet.Razor package to "4.0.0-beta5"
 * Run build.cmd
 * Take RazorEngine.dll from src\source\RazorEngine.Core\obj\Razor4\Release\RazorEngine.dll  and referenced it in my project.
 * The project has compiled well but I still get the same error ("Could not load type...") when tried to run that simple example.

**Comment by matthid** [comment]
> Changed the version of reference Microsoft.AspNet.Razor package to "4.0.0-beta5"

You would need to change the references in the `*.csproj` files as well (and just to be sure delete "-beta1" folder). I would suggest to just edit the HintPath by hand.

It shouldn't build with the latest version as we definitely use this class [here](https://github.com/Antaris/RazorEngine/blob/master/src/source/RazorEngine.Core/Compilation/CSharp/CSharpCodeParser.cs#L26) and it has changed to another namespace.

If you happen to do these changes a pull request would be very welcome :+1: 

Hope this helps
