### ISSUE TITLE
Where's RazorEngine's changelog

### ISSUE THREAD

**Issue by litera** [Antaris/RazorEngine#304]
After upgrading to latest version my app started breaking as it can't compile a layout as it uses some type that is in a namespace that is configured under `razorEgine/namespaces/add`. It used to work, but now unless I specify my class with full namespace path it breaks.

A changelog would help so we'd know in which ways our apps can break when we upgrade versions.

> But just a sidenote: my exception still isn't resolved. The above mentioned workaround (full namespace path) is put in place but that's not supposed to be final solution.

**Comment by matthid** [comment]
Can you provide the layout? The changelog is [here](https://github.com/Antaris/RazorEngine/blob/master/doc/ReleaseNotes.md), in the [docs](https://antaris.github.io/RazorEngine/ReleaseNotes.html) and on NuGet (for every version).

**Comment by litera** [comment]
### About changelog
The usual place where GitHub projects have their changelog is when one clicks releases where authors can provide all these that you have in a separate doc.

### Type accessibility issue
Let me provide an excerpt of my layout which is nothing particularly special (it's an email template):

```HTML
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	... Mailchimp style reset block...
</head>
<body>
	<table cellspacing="0" cellpadding="0" border="0" id="backgroundTable">
		<tr>
			<td valign="top">
				@RenderBody()
				<hr align="left" size="1" style="height: 1px; width: 100px;" />
				<p>
					<a href="@MessagingConfigurationSection.Current.AppRoot"><strong>Dogtag</strong></a><br />
					<em>Dogs, but modernised</em>
				</p>
			</td>
		</tr>
	</table>
</body>
```

As you can see I don't have any usings at the top, as I configured `razorEngine` in my *web.config* that is also sending emails using Razor Engine:

```XML
<razorEngine>
	<namespaces>
		<add namespace="DogTag.Messaging.Configuration" />
		<add namespace="DogTag.Models.Content" />
		<add namespace="DogTag.Models.Extensions" />
	</namespaces>
</razorEngine>
```

`DogTag.Messaging.Configuration` namespace is the one where specific `MessagingConfigurationSection` class is defined that layout uses.

So my workaround for now is that I provide full type name in that specific link:
```HTML
<a href="@DogTag.Messaging.Configuration.MessagingConfigurationSection.Current.AppRoot"><strong>Dogtag</strong></a>
```
and then it works. So somehow configuration is not being used with the layout (and maybe even on templates that use this layout as well...

One more thing that may interest you is how I cache this layout. My layouts are part of my own configuration which defines layout file app-relative paths that reads them fine:
```csharp
// precompile layout template
foreach(LayoutConfigurationElement layout in MessagingConfigurationSection.Current.Layouts)
{
	if (!Engine.Razor.IsTemplateCached(layout.Path, null))
	{
		Engine.Razor.Compile(
			File.ReadAllText(HostingEnvironment.MapPath(layout.Path)),
			layout.Path);
	}
}
```
And my app breaks on the `Compile` statement as RazorEngine is unable to compile the layout because of the aforementioned problem.

**Comment by matthid** [comment]
But the [releases](https://github.com/Antaris/RazorEngine/releases) page contains the changelog as well, or am I missing something? Do you want to change the title or open another issue and close this?

Was the latest working version 3.6 or something earlier, then yes this change could very well be it.
Note I removed this feature to be able to move to apache2 (because the author did not react). Of course I would accept a PR reimplementing the feature. Sorry, but I have not planned to implement this feature.

Configuration fallback to XML means exactly that: When no configuration is set by code -> use the XML based configuration.

**Comment by litera** [comment]
@matthid You're right. One has to click those ellipsis to unhide info... :) I'm used to these kind of releases page, that shows everything right away, so that's why I didn't think of clicking those ellipsis.

But yes. We should create a separate issue for the problem I'm having. Let me do it. I'll close this one and open a new one.

**Comment by litera** [comment]
#305 created.

**Comment by matthid** [comment]
The release process is completely automated, so I have no idea what I need to do to make github show it in another way (currently simple tags are created and pushed). Can it be automated?

**Comment by litera** [comment]
It is automated, but in order for the info to show with all the details already open, you have to provide **release details** otherwise you'll only see commit messages collapsed as they're displayed at the moment. See [this releases page](https://github.com/danialfarid/ng-file-upload/releases). I think this kind of releases page look much nicer and usable as you can see everything immediately and nicely formatted as developers can provide emphasis on certain parts that they think are important.

Doing it this way you can always create release sections: *New features*, *Resolved bugs*, *Breaking changes* which makes it even more interesting.

**Comment by matthid** [comment]
https://developer.github.com/v3/repos/releases/#create-a-release, but I think we need username and password in the build process to use this API. Maybe sometimes in the future I check if this can be integrated in my current release process (which is automated completely, and should stay like this).
