### ISSUE TITLE
Getting started, but then isolated

### ISSUE THREAD

**Issue by Sunib** [Antaris/RazorEngine#307]
I'm trying to get started with RazorEngine but I'm having a problem with running it in a sandbox.

My situation:
* Started with an empty console application in C#
* Installed RazorEngine 4.2.0-beta2 using NuGet.
* Working in a single [Program.cs](https://gist.github.com/Sunib/6fbd3491deac3849a588) that contains some copy/paste actions from the documentation that I could find in the wiki.
* Templating already works fine, but my templates are now so powerfull that they also can create files on my file system. Which I really don't want in the web environment where it's going to be used.

I read and applied the [isoluation page](https://antaris.github.io/RazorEngine/Isolation.html). But must admit that I'm not an expert on these sandbox topics.

First I didn't got strong names, after applying [this so advice](http://stackoverflow.com/questions/8349573/getting-null-from-gethostevidence) I stumbled upon these errors.
```
Error	1	Assembly generation failed -- Referenced assembly 'RazorEngine' does not have a       strong name	D:\git\presence-engine\RazorExperiment\CSC	RazorExperiment
Error	2	Assembly generation failed -- Referenced assembly 'Microsoft.AspNet.Razor' does not have a strong name	D:\git\presence-engine\RazorExperiment\CSC	RazorExperiment
```

Could someone give me some hints?

**Comment by matthid** [comment]
Yes, apparently the Microsoft.AspNet.Razor beta nuget package is not signed therefore you can't use sandboxing with it. You have two options: Either compile Micosoft.AspNet.Razor yourself and sign it (as it is open source) or use the latest stable package.

**Comment by matthid** [comment]
I forgot to say: We cannot sign RazorEngine in this scenario because we depend on an unsigned reference, so if you go for option 1 you need to sign RazorEngine as well.

**Comment by Sunib** [comment]
Thank you for your hints, it now works! I get an FileIO exception when trying to write something to a file. Just like I wanted. +1: 

For future readers, first deinstall your beta and then open up your Package Manager Console and enter (you might want to check [this page](https://www.nuget.org/packages/RazorEngine/) to see the latest release): 
```
Install-Package RazorEngine -Version 3.7.0
```

Btw. It's interesting that I got a beta while just using the simple "Manage NuGet packages" window, I would expect it to install the latest stable by default.
