### ISSUE TITLE
Version 3.7.2 is 50% slower than 3.3.0

### ISSUE THREAD

**Issue by RoboBurned** [Antaris/RazorEngine#327]
I am switching app from using version 3.3.0 to 3.7.2. The API was changed and I had to refactor my code. After performing some tests I got about 30 to 50% performance degradation of new version.
Here are test code

```csharp
// 3.3.0 -- 12 sec --
		public static void Test()
		{
			TemplateServiceConfiguration templateConfig = new TemplateServiceConfiguration();
			Razor.SetTemplateService(new TemplateService(templateConfig));
			string template = "Hello @Model.Name, welcome to RazorEngine!";
			string bigTemplate = string.Join(Environment.NewLine, Enumerable.Range(1, 50).Select(m => template));
			var model = new Model { Name = "World" };
			for (int i = 0; i <= 1000000; i++)
			{
				var result = RazorEngine.Razor.Parse(bigTemplate, model, "templateKey");
			}
		}

// 3.7.2 -- 18 sec--
			TemplateServiceConfiguration templateConfig = new TemplateServiceConfiguration();
			IRazorEngineService service = RazorEngineService.Create(templateConfig);
			Engine.Razor = service;

			string template = "Hello @Model.Name, welcome to RazorEngine!";
			string bigTemplate = string.Join(Environment.NewLine, Enumerable.Range(1, 50).Select(m => template));
			var model = new Model { Name = "World" };
			for (int i = 0; i <= 1000000; i++)
			{
				var result =
					Engine.Razor.RunCompile(bigTemplate, "templateKey", typeof(Model), model);
			}
```
The first example runs much faster.
My actual code uses custom template manager, resolver and template source. These parts could also become slower in new version but I started investigation with this simple code.
Do I use new API wrong or there is an issue with performance?

**Comment by dyardyGIT** [comment]
Very interested in reply.

**Comment by matthid** [comment]
The API shifted to a "higher" abstraction level and therefore a bit of an performance hit is expected. Are you hit by this issue or are you just curious?
The following code should perform a bit better:

```csharp
            var watch = System.Diagnostics.Stopwatch.StartNew();
            TimeSpan first, total;
            const int NUM = 1000000;

            TemplateServiceConfiguration templateConfig = new TemplateServiceConfiguration();
            templateConfig.Debug = false;
            templateConfig.DisableTempFileLocking = true;
            templateConfig.CachingProvider = new DefaultCachingProvider(s => { });
            IRazorEngineService service = RazorEngineService.Create(templateConfig);
            Engine.Razor = service;

            string template = "Hello @Model.Name, welcome to RazorEngine!";
            string bigTemplate = string.Join(Environment.NewLine, Enumerable.Range(1, 50).Select(m => template));
            var model = new Model { Name = "World" };
            var key = Engine.Razor.GetKey("templateKey");
            Engine.Razor.RunCompile(bigTemplate, key, typeof(Model), model);
            first = watch.Elapsed;
            for (int i = 0; i <= NUM; i++)
            {
                Engine.Razor.Run(key, typeof(Model), model);
            }

            watch.Stop();
            total = watch.Elapsed;
            Console.WriteLine("First: {0}, Total: {1} ({2} ms per call)", first, total, total.TotalMilliseconds / (double)NUM);
            Console.ReadKey();
```

I'm pretty sure there is some room to optimize the current codebase to get back some of the performance if you really need it, though.

**Comment by RoboBurned** [comment]
Template processing in my app is made synchronously so every ms will force users to wait. If it is not possible to optimize this, I will prefer to stay on the old version.
Unfortunately the code provided above do not help much. Main degradation is in execution, not compiling template.
I found two slow places: CreateTemplate method and data manipulation in TemplateBase.Run method.
I have no code of original 3.3.0 version but I see changes in Run method:
StringBuilder and StringWriter around it was used originally and seems to be faster than MemoryStream and stream manipulation around it.

**Comment by matthid** [comment]
> so every ms will force users to wait

But we are not in the `ms` range here, right? Are your templates so big that you are in that range in production?

**Comment by matthid** [comment]
Released in https://www.nuget.org/packages/RazorEngine/3.7.3
