### ISSUE TITLE
Extending the template Syntax doesn't work in loops

### ISSUE THREAD

**Issue by Trollier** [Antaris/RazorEngine#329]
Hello,

I extended the syntax in order to implement some customed features.

MyHtmlHelper class:
<code>
 public IEncodedString PascalName(string name)
       {
           name+= "Mister";
            return new RawString(name);
       } 
</code>

HtmlSupportTemplateBase class:
<code>
    public class HtmlSupportTemplateBase <T> : TemplateBase<T>
    {
        public HtmlSupportTemplateBase()
        {
            Html = new MyHtmlHelper();
        }

        public MyHtmlHelper Html { get; set; }
    }
</code>

The implementation:
<code>
            var config = new TemplateServiceConfiguration();
            config.BaseTemplateType = typeof(HtmlSupportTemplateBase<>);
            using (var service = RazorEngineService.Create(config))
            {
                var codeTypeListContent = Generator.Shared.Library.Deserialize(_data, typeof(CodeTypesContent)) as CodeTypesContent;
                var codeTypeModel = new CodeTypeModel { CodeTypeLists = codeTypeListContent.CodeType };
                string template = "salut";
                string generatedCode = service.RunCompile(template, "htmlRawTemplate", null, codeTypeModel);
                string outputFile = "C:\\polo.txt";
                WriteTextToFile(outputFile, generatedCode);
                return new[] { outputFile };
            }
</code>

The template : 
<code>
@foreach( var person in Model.personsEnumerable){
@:   @Html.PascalName(person.nom)
}
</code>

The issue is that when I use the extension outside the loop t works but when using it in the foreach loop it doesn't work and raise an exception "A first chance exception of type 'System.ArgumentException' occurred in RazorEngine.dll".

Thank you.

**Comment by matthid** [comment]
Can you try `<text></text>` instead of `@:`. I remember having problems with the `@:` syntax before.

```
@foreach( var person in Model.personsEnumerable){ <text>@Html.PascalName(person.nom)</text> }
```

**Comment by Trollier** [comment]
thx it works :)
