### ISSUE TITLE
CrossAppDomainCleanup.CleanupHelper.IsUnloaded throws an AppDomain unloaded exception while debugging

### ISSUE THREAD

**Issue by gotvino** [Antaris/RazorEngine#333]
Version 3.7.3.0:
While debugging an application that uses RazorEngine in Visual Studio 2013, an AppDomainUnloaded exception occurs while unloading the AppDomain it runs under:

`RazorEngine.dll!RazorEngine.Compilation.CrossAppDomainCleanUp.CleanupHelper.IsUnloaded(System.AppDomain domain = {System.Runtime.Remoting.Proxies.__TransparentProxy})	UnknownRazorEngine.dll!RazorEngine.Compilation.CrossAppDomainCleanUp.CleanupHelper.domain_DomainUnload.AnonymousMethod__0()	Unknown
mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
mscorlib.dll!System.Threading.ThreadHelper.ThreadStart()	Unknown
`

It also occurs if RazorEngine runs under the default app domain when the application exits.

The temporary RazorEngine assemblies in the temp folder fail to get cleaned up.

This does not occur when executing normally (not attached to debugger).

**Comment by aviatrix** [comment]
context please ?

**Comment by gotvino** [comment]
My apologies, accidentally pressed <Enter>. Updated comment above. Let me know if you need any additional information.

**Comment by gotvino** [comment]
I have a bit more information. The problem occurs when attached to a debugger. RazorEngine is not able to remove the temporary assembly files. Two exceptions are thrown (unauthorized exception to the path, then an appuloaded exception as stated above. The issue does not occur when running normally thus the impact is minimal.
