### ISSUE TITLE
Build errors on master branch

### ISSUE THREAD

**Issue by BrettBock** [Antaris/RazorEngine#341]
What do I need to fix in my environment to get the master branch to build in Visual Studio 2013?

It appears the solution does not contain the proper references.  Getting the latest master branch and building produces the following 58 errors:
`Error	6	The type or namespace name 'NUnit' could not be found (are you missing a using directive or an assembly reference?)	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	1	7	Test.RazorEngine.Core
Error	7	The type or namespace name 'TestFixture' could not be found (are you missing a using directive or an assembly reference?)	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	29	6	Test.RazorEngine.Core
Error	8	The type or namespace name 'TestFixtureAttribute' could not be found (are you missing a using directive or an assembly reference?)	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	29	6	Test.RazorEngine.Core
Error	9	The name 'Assert' does not exist in the current context	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	49	17	Test.RazorEngine.Core
Error	10	The name 'Assert' does not exist in the current context	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	52	17	Test.RazorEngine.Core
Error	11	'Test' is not an attribute class	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	98	10	Test.RazorEngine.Core
Error	12	The name 'Assert' does not exist in the current context	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	108	17	Test.RazorEngine.Core
Error	13	'Test' is not an attribute class	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	115	10	Test.RazorEngine.Core
Error	14	The name 'Assert' does not exist in the current context	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	126	17	Test.RazorEngine.Core
Error	15	'Test' is not an attribute class	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	133	10	Test.RazorEngine.Core
Error	16	The name 'Assert' does not exist in the current context	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	144	17	Test.RazorEngine.Core
Error	17	'Test' is not an attribute class	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	151	10	Test.RazorEngine.Core
Error	18	The name 'Assert' does not exist in the current context	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	163	17	Test.RazorEngine.Core
Error	19	The name 'Assert' does not exist in the current context	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	168	17	Test.RazorEngine.Core
Error	20	The name 'Assert' does not exist in the current context	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	207	21	Test.RazorEngine.Core
Error	21	The name 'Assert' does not exist in the current context	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	218	25	Test.RazorEngine.Core
Error	22	The name 'Assert' does not exist in the current context	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	222	25	Test.RazorEngine.Core
Error	23	The name 'Assert' does not exist in the current context	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	225	17	Test.RazorEngine.Core
Error	24	The name 'Assert' does not exist in the current context	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	228	21	Test.RazorEngine.Core
Error	25	'Test' is not an attribute class	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	236	10	Test.RazorEngine.Core
Error	26	'Test' is not an attribute class	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	256	10	Test.RazorEngine.Core
Error	27	The name 'Assert' does not exist in the current context	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	271	17	Test.RazorEngine.Core
Error	28	The name 'Assert' does not exist in the current context	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	276	17	Test.RazorEngine.Core
Error	29	'Test' is not an attribute class	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	283	10	Test.RazorEngine.Core
Error	30	The name 'Assert' does not exist in the current context	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	300	17	Test.RazorEngine.Core
Error	31	'Test' is not an attribute class	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	308	10	Test.RazorEngine.Core
Error	32	The name 'Assert' does not exist in the current context	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	318	17	Test.RazorEngine.Core
Error	33	'Test' is not an attribute class	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	325	10	Test.RazorEngine.Core
Error	34	The name 'Assert' does not exist in the current context	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	333	17	Test.RazorEngine.Core
Error	35	The name 'Assert' does not exist in the current context	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	336	21	Test.RazorEngine.Core
Error	36	'Test' is not an attribute class	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	344	10	Test.RazorEngine.Core
Error	37	The name 'Assert' does not exist in the current context	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	353	17	Test.RazorEngine.Core
Error	38	The name 'Assert' does not exist in the current context	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	356	21	Test.RazorEngine.Core
Error	39	'Test' is not an attribute class	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	365	10	Test.RazorEngine.Core
Error	40	The name 'Assert' does not exist in the current context	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	375	17	Test.RazorEngine.Core
Error	41	'Test' is not an attribute class	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	383	10	Test.RazorEngine.Core
Error	42	The name 'Assert' does not exist in the current context	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	393	17	Test.RazorEngine.Core
Error	43	'Test' is not an attribute class	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	400	10	Test.RazorEngine.Core
Error	44	The name 'Assert' does not exist in the current context	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	410	17	Test.RazorEngine.Core
Error	45	'Test' is not an attribute class	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	418	10	Test.RazorEngine.Core
Error	46	The name 'Assert' does not exist in the current context	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	429	17	Test.RazorEngine.Core
Error	47	'Test' is not an attribute class	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	436	10	Test.RazorEngine.Core
Error	48	The name 'Assert' does not exist in the current context	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	443	17	Test.RazorEngine.Core
Error	49	'Test' is not an attribute class	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	454	10	Test.RazorEngine.Core
Error	50	The name 'Assert' does not exist in the current context	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	464	17	Test.RazorEngine.Core
Error	51	'Test' is not an attribute class	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	471	10	Test.RazorEngine.Core
Error	52	The name 'Assert' does not exist in the current context	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	481	17	Test.RazorEngine.Core
Error	53	'Test' is not an attribute class	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	495	10	Test.RazorEngine.Core
Error	54	The name 'Assert' does not exist in the current context	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	506	17	Test.RazorEngine.Core
Error	55	'Test' is not an attribute class	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	519	10	Test.RazorEngine.Core
Error	56	The name 'Assert' does not exist in the current context	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	529	17	Test.RazorEngine.Core
Error	57	'Test' is not an attribute class	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	542	10	Test.RazorEngine.Core
Error	58	The name 'Assert' does not exist in the current context	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	545	13	Test.RazorEngine.Core
Error	59	'Test' is not an attribute class	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	561	10	Test.RazorEngine.Core
Error	60	The name 'Assert' does not exist in the current context	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	564	13	Test.RazorEngine.Core
Error	61	'Test' is not an attribute class	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	591	10	Test.RazorEngine.Core
Error	62	The name 'Assert' does not exist in the current context	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	594	13	Test.RazorEngine.Core
Error	63	The name 'Assert' does not exist in the current context	D:\FreelandCode2008\OpenSource\GitHub\RazorEngine\src\test\Test.RazorEngine.Core\IsolatedRazorEngineServiceTestFixture.cs	603	25	Test.RazorEngine.Core
`

**Comment by matthid** [comment]
Did you run a build before opening the solution as written in the https://antaris.github.io/RazorEngine/DevelopReadme.html ? (ie just doubleclick build.cmd before opening the solution)

**Comment by BrettBock** [comment]
Yes, using build at the root got it working so that I can now use the .sln file in Visual Studio 2013.  Did not see that bit in the Development Intro.  Thank you.

I am seeing the following warnings:
`Warning	1	The referenced component 'Microsoft.Practices.Unity.Configuration' could not be found. 	Test.RazorEngine.Core
Warning	2	The referenced component 'Microsoft.Practices.Unity' could not be found. 	Test.RazorEngine.Core
Warning	3	The referenced component 'Microsoft.Practices.Unity.RegistrationByConvention' could not be found. 	Test.RazorEngine.Core
`
