### ISSUE TITLE
Model with a class property that is null throws exception

### ISSUE THREAD

**Issue by BrettBock** [Antaris/RazorEngine#343]
Any idea how to fix code so the unit test below works?

Running the unit test below produces the following exception:
Unable to cast object of type 'RazorEngine.Tests.TestTypes.ComplexModel' to type 'RazorEngine.Tests.TestTypes.Person'

It appears the ```TemplateBase<T>.Include()``` method is receiving a generic model with no type information.  The code works fine when model.Person is not null e.g. by uncommenting the model.Subject line.  I am not able to step into the code that calls ```TemplateBase<T>.Include()```.
```c#
namespace RazorEngine.Tests.TestTypes
{
	/// <summary>
	/// Model that has properties that are classes vice simple types
	/// </summary>
	public class ComplexModel
	{
		/// <summary>
		/// Person who is the subject for this model
		/// </summary>
		public Person Subject { get; set; }
	}
}

namespace RazorEngine.Tests
{
        [Test]
        public void TemplateBase_CanRenderWithInclude_WithCustomModel_WithNull()
        {
            using (var service = new TemplateService())
            {
				const string child = "@model RazorEngine.Tests.TestTypes.Person\n<div>Content from child for @Model.Forename</div>";
				const string template = "@Include(\"Child\", @Model.Subject)";
                const string expected = "<div>Content from child for </div>";

				var model = new RazorEngine.Tests.TestTypes.ComplexModel();
				//model.Subject = new Person() { Forename = "" };

                service.GetTemplate(child, null, "Child");
                string result = service.Parse(template, model, null, null);

                Assert.AreEqual(expected, result);
            }
        }
}
```

**Comment by BrettBock** [comment]
Created a work-around by adding the below override to a `TemplateBase<>` derived class and setting `TemplateServiceConfiguration.BaseTemplateType` to use the new template.

Is there a better way to do this?  Should this code be moved down into `TemplateBase<T>`?

```C#
public override TemplateWriter Include(string name, object model = null, Type modelType = null)
{
	if (null == model && modelType != null)
		model = Activator.CreateInstance(modelType);

	return base.Include(name, model, modelType);
}
```

**Comment by matthid** [comment]
I knew this would come back one way or another. The problem is we can not differentiate between `null` and a not given argument. So in your case we assume `null` means that the argument was not given, when in fact it was.

I think we should get rid of the optional arguments and make it explicit and 3 overloads (this will be a breaking change though)

**Comment by matthid** [comment]
FYI: Without the bug your example throws a `NullReferenceException` because the `@Model` is `null` and you try to access `.Forename`. So in order to make it work with the next update you need to use `@(Model == null ? "" : Model.Forename)`.
Is this what you expected?

**Comment by matthid** [comment]
https://www.nuget.org/packages/RazorEngine/3.7.5-beta2

**Comment by BrettBock** [comment]
Success!  Using the 3.7.5 beta works for our unit tests now even after removing the work-around.  Thank you.  We can close when 3.7.5 is released.
The example code originally had the null check, but was removed to make the example more clear.  Additionally, the work-around never passes null.

**Comment by matthid** [comment]
Thanks for reporting an providing a unit test :)
