### ISSUE TITLE
Model failing to cross app domain boundary when containing nested objects

### ISSUE THREAD

**Issue by knightmeister** [Antaris/RazorEngine#344]
I am using the RazorDynamicObject to wrap my model objects. When it is a straight forward model with no nested classes, it works. However, when I have a nested object (i.e. a complex type) within my model it fails with an exception Could not load file or assembly 'Models, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

I posted it on Stackoverflow here - http://stackoverflow.com/questions/34058426/isolated-razorengine-failing-to-pass-model-to-different-appdomain - it has a bounty on it at the moment.

I think this is an issue in RazorEngine - either in the documentation or the implementation of RazorDynamicObject.

**Comment by matthid** [comment]
I think the question was answered on stackoverflow, the reason was shadow copying. It was already discussed (including possible solutions) here: https://github.com/Antaris/RazorEngine/issues/224
