### ISSUE TITLE
how can i use the '@section' feature?

### ISSUE THREAD

**Issue by hellojiaru** [Antaris/RazorEngine#346]
```
@section section1{
//content
}
```
how can i get the content  after executing the RunCompile method?or anyway else to RenderSection in other templates just like what we do in mvc webpages

**Comment by matthid** [comment]
If the question is about using RenderSection you can just use it in Templates like you do in MVC. Can you explain what you are trying to achieve with sample code?

**Comment by matthid** [comment]
If the question is about getting data OUT of the template (like in https://github.com/Antaris/RazorEngine/issues/238). The following code is the way to do it (currently this fails because of #348 but will release a fix shortly):

```csharp

    public class Program
    {
        public class TemplateContext<T> : TemplateBase<T>
        {
            public string Section1
            {
                set {
                    ((CustomDataHolder)ViewBag.DataHolder).Section1 = value;
                }
            }
        }

        public class CustomDataHolder
        {
            public string Section1 { get; set; }
        }

        static void Main(string[] args)
        {
            using (var service = RazorEngineService.Create
                (new TemplateServiceConfiguration() { Debug = true }))
            {
                const string template = @"
@{ Layout = ""extractLayouts""; }
@section section1{
<text>sample content</text>
}
            ";
                const string sectionExtracting = @"
@inherits TestRunnerHelper.Program.TemplateContext<dynamic>
@{
    string result;
    using (var mem = new System.IO.StringWriter())
    {
        System.Diagnostics.Debugger.Break();
        var section1 = RenderSection(""section1"");
        section1.WriteTo(mem);
        mem.Flush();
        Section1 = mem.ToString();
    }
}

@RenderSection(""section1"")";
                service.Compile(sectionExtracting, "extractLayouts", null);

                var holder = new CustomDataHolder();
                dynamic viewbag = new DynamicViewBag();
                viewbag.DataHolder = holder;
                var body = service.RunCompile(template, "templateKey", null, null, (DynamicViewBag)viewbag);


                if (!holder.Section1.Contains("sample content"))
                {
                    throw new Exception("Expected section content");
                }
            }
        }
    }
```

**Comment by matthid** [comment]
The code now works with https://www.nuget.org/packages/RazorEngine/3.7.6

**Comment by hellojiaru** [comment]
thanks matthid,it works in 3.7.6,and it's great help for me.i'm doing sth like mvc6's taghelper,turning tags into html and script,some tags even need a script refference or css refference,so i have to seperate them by '@section',but is there any idea to do this without defining a Layout?i don't want  to add that string into all of my templates

**Comment by matthid** [comment]
Yes this is possible with a custom TemplateBase implementation. Please look into https://antaris.github.io/RazorEngine/TemplateBasics.html#Extending-the-template-Syntax and the discussion here: https://github.com/Antaris/RazorEngine/issues/289

Feel free to ask further if those resources are not helpful.
Note: I think we will support taghelpers directly as soon as we support Razor4.

**Comment by matthid** [comment]
So to clarify: I suggest that you force your templates into using a specific layout, which looks like `sectionExtracting` template from my example code to extract the data you want. This way you don't need to change your templates.

**Comment by hellojiaru** [comment]
Finally i did append the layout defining string to the top of my templates before compile, and it seems work well by now :)

**Comment by matthid** [comment]
Yep that works as well, I think this can be closed.
