### ISSUE TITLE
Method not found: 'Void Microsoft.AspNet.Razor.CodeGenerators.GeneratedClassContext.set_ResolveUrlMethodName(System.String)'.

### ISSUE THREAD

**Issue by fenix2222** [Antaris/RazorEngine#351]
I am getting the following exception when running latest 4.2.6-beta1 with Microsoft.AspNet.Razor 4.0.0-rc1-final:

Method not found: 'Void Microsoft.AspNet.Razor.CodeGenerators.GeneratedClassContext.set_ResolveUrlMethodName(System.String)'.

**Comment by matthid** [comment]
Duplicate of https://github.com/Antaris/RazorEngine/issues/322
