### ISSUE TITLE
MvcHtmlString getting encoded

### ISSUE THREAD

**Issue by billrob** [Antaris/RazorEngine#355]
When using MvcHtmlString in mvc razor views, the contents are not encoded.
When using the RazorEngine it is not treating the content as already been encoded.

The part to change is on line 425 on TemplateBase.cs.

Current:
   if (value is IEncodedString)
Proposed
   if(value is IEncodedString || value is IHtmlString)

I will generate a pull request if this is moving in the correct direction.

Thanks.

**Comment by matthid** [comment]
I think we don't have a reference to `IHtmlString` in RazorEngine as we don't reference MVC (only the Razor Engine). I think you can solve this by using your own subclass from TemplateBase. 

Closing as this quite old.

**Comment by billrob** [comment]
Sorry about not closing this out.  I saw it didn't have that reference and found another solution.
