### ISSUE TITLE
Visual Studio 2015 - Unable to hit breakpoint in Razor template

### ISSUE THREAD

**Issue by trankdog** [Antaris/RazorEngine#360]
Breakpoints are never hit in Razor template when using Visual Studio 2015, same breakpoints are hit when project is opened in VS2013.

**Comment by bastienJS** [comment]
I experience the same problem!

Is this only fixable by MS?

```
  var config = new TemplateServiceConfiguration();
            // .. configure your instance
            config.Debug = true;
            var service = RazorEngineService.Create(config);
            Engine.Razor = service;

            string template = File.ReadAllText("./index.cshtml");
            var viewModel = new CustomerViewModel { Id = 34356789 };

           var source = new LoadedTemplateSource(template, "./index.cshtml");
            var result = Engine.Razor.RunCompile(source, "dklr4w3j3io34", viewModel.GetType(), viewModel, null);
```

Inside the index.cshtml I have a breakpoint, it never stops there!

**Comment by bastienJS** [comment]
After googling using VS2015 Update 2 - so everything up to date... - that was my solution.

![image](https://cloud.githubusercontent.com/assets/5945955/15053287/252a7fca-1302-11e6-832c-508144c6bfc5.png)

Just enable the red outlined option and the debugger stops in the .cshtml file!

**Comment by marcosbozzani** [comment]
The @bastienJS solution should be in the official docs/wiki

**Comment by JamesYuen** [comment]
@bastienJS Great solution!

**Comment by HotSpotSoft** [comment]
I'm having the same issue with VS2017 version 15.2. Checking the option provided above did not solve the problem for me. Is there something i have missed ?

**Comment by triynko** [comment]
Also experiencing the problem in VS 2017   v15.2.   Cannot debug any CSHTML files.  Tried cleaning, rebuilding, restarting everything, and tried the debugging option mentioned above.

**Comment by ghost** [comment]
I had similar problem. I fixed it by adding reference of dll System.web.razor

**Comment by davidon** [comment]
@bhaktiu  can you have more detailed description on how to "adding reference of dll System.web.razor"?

**Comment by rvnlord** [comment]
I have the same problem in Visual Studio 2019, the reason is that I moved my Views folder to another directory. Please provide a fix because this is a regression from older versions of Visual Studio. UI actually shows that breakpoints will be hit but they aren't (there is NO warning on breakpoints) and pdbs are generated correctly. Also there is a problem related to this: if you move Views to another directory 'Add View' menu item won't appear any longer.
