### ISSUE TITLE
Error "Feature 'implicitly typed local variables' is unavailable".

### ISSUE THREAD

**Issue by otac0n** [Antaris/RazorEngine#363]
When I open a template that uses `var`, I get the error message mentioned in the title.

I found that this is necessary in the project's app.config:

```
  <system.codedom>
    <compilers>
      <compiler language="c#;cs;csharp" extension=".cs;cshtml" type="Microsoft.CSharp.CSharpCodeProvider,System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" warningLevel="4">
        <providerOption name="CompilerVersion" value="v4.5" />
        <providerOption name="WarnAsError" value="false" />
      </compiler>
    </compilers>
  </system.codedom>
  <system.web>
    <compilation targetFramework="4.5">
      <assemblies>
        <add assembly="System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
      </assemblies>
    </compilation>
    <httpRuntime targetFramework="4.5" />
  </system.web>
```

Could you update the https://antaris.github.io/RazorEngine/IntellisenseAndResharper.html page to include this information?

**Comment by cyrilgandon** [comment]
I made two projects, one have the error, the other not.

In both case I didn't use app.config at all, Don't ask me why or how or what the hell, but it works in one, not the other. You can try this solution, where the use of `var` works: https://github.com/cyrilgandon/RazorEngineGenerator

**Comment by apryiomka** [comment]
any update on this? I have the same issue where the template doesn't compile. I cannot use 'var' as well as 'null propagating operator' (object?.value)

**Comment by matthid** [comment]
Closing in favor of https://github.com/Antaris/RazorEngine/issues/368
