### ISSUE TITLE
Question: Duplicate key after invalidating cache

### ISSUE THREAD

**Issue by wakemaster39** [Antaris/RazorEngine#367]
Hello,

What I am trying to do is write some tests around my usage of the RazorEngine. The issue I am running in to is that my tests invoke the same unique key for a set of templates. I have set up the system using the following: 

    [TestFixture]
    class Tests
    {
        private static IRazorEngineService Service { get; set; }
        private static InvalidatingCachingProvider Provider { get; set; }
        private static TemplateServiceConfiguration Configuration { get; set; }

        [OneTimeSetUp]
        public void SetUpFixture()
        {
            Provider = new InvalidatingCachingProvider();
            Configuration = new TemplateServiceConfiguration()
            {
                Debug = true,
                Language = Language.CSharp,
                EncodedStringFactory = new RawStringFactory(),
                CachingProvider = Provider
            };
            
            Service = RazorEngineService.Create(Configuration);
            Engine.Razor = Service;
        }
        [TearDown]
        public void TearDown()
        {
            Provider.InvalidateAll();
        }
    }

If I run multiple tests calling compile on the same key, I run into a duplicate key error. I understand that the InvalidateAll() causes a memory leak, and I am not overly concerned with this problem, but I thought by calling the invalidate it would allow me to use a duplicate key. 

Is this key bound to the loaded assembly name which is why I am running into a collision issue?
Is there a way that I can write a test that will invoke a duplicate key?

Thanks for the help.

**Comment by matthid** [comment]
The default template manager is caching the given template source text https://github.com/Antaris/RazorEngine/blob/master/src/source/RazorEngine.Core/Templating/DelegateTemplateManager.cs#L68. This is to fail early as it would be wrong to later use the cache when source changed.

Either use another TemplateManager or call `RemoveDynamic`.
