### ISSUE TITLE
checking for template

### ISSUE THREAD

**Issue by tofutim** [Antaris/RazorEngine#377]
Is it possible to just check for the template and not compile it if it already exists? This seems really redundant

            var subjectKey = campaign.CampaignId.ToShortString() + "_subject";
            if (Engine.Razor.IsTemplateCached(subjectKey, typeof(v8_Offer)))
            {
                subject = Engine.Razor.Run(subjectKey, typeof(v8_Offer), offer);
            } 
            else
            {
                subject = Engine.Razor.RunCompile(campaign.Subject, subjectKey, typeof(v8_Offer), offer);
            }

How about an overwrite flag, or don't compile if exists flag?

**Comment by matthid** [comment]
RunCompile does this check already,

**Comment by matthid** [comment]
Closing old issue.
