### ISSUE TITLE
clearing cache for certain keys

### ISSUE THREAD

**Issue by tofutim** [Antaris/RazorEngine#378]
Hi, I track my templates in a database, but these sometimes change. How can I reset the cache for these keys without having to restart the whole appdomain?

**Comment by tofutim** [comment]
Giving up and using the MD5 method for a bit.

**Comment by matthid** [comment]
This is by design, you might wanna write your own template manager for your use case. Please read https://antaris.github.io/RazorEngine/TemplateManager.html
