### ISSUE TITLE
How to support libs used in the template that are only known at runtime?

### ISSUE THREAD

**Issue by fatso83** [Antaris/RazorEngine#380]
Thanks for a great library. I have used it to create a [50 line CLI app](https://github.com/fatso83/razor-cli/blob/master/razor-cli.cs) that compiles razor templates into static html, for instance to be used in static style guides. The basic functionality works great, but the partials could be using any number of libraries and extension methods, and of course [this will fail (as-is)](https://github.com/fatso83/razor-cli/issues/1).

I am fully aware that supporting `Html.Raw` (and friends) have been a recurring theme in the issues tracker, and that this is not the concern of the parser, and so I have been reading up on how one can [extend the base template class](https://antaris.github.io/RazorEngine/TemplateBasics.html#Extending-the-template-Syntax) to support this. From what I can gather, when extending the template one must already know which API one is supporting at compile time, but this is info only available at runtime (as I have no way knowing what kind of libs are being used beforehand).

Is there any way of achieving this? At first I thought that simply adding the location of `System.Web.Mvc.dll` would be enough to support its helpers (exclusive of any extension methods), but that did not seem to have any effect. I am no .NET programmer, which might explain why :-/

**Comment by kellysalvage** [comment]
If you are compiling and executing your templates in the same app, you will need to resolve the assemblies that your generated code reference at runtime. This can be done using the AssemblyResolve event of the appdomain of your application [https://msdn.microsoft.com/en-us/library/system.appdomain.assemblyresolve(v=vs.110).aspx](url)

If you are building a project and are generating a project file, then you will need to generate project references to the assemblies.

**Comment by fatso83** [comment]
Thanks, I will look into this.
