### ISSUE TITLE
QuestionL:

### ISSUE THREAD

**Issue by bastienJS** [Antaris/RazorEngine#381]
This code still worked in December 2015:

```
[var result1 = Engine.Razor.RunCompile(template, "templateKey", null, new { Name = "Hello" }); // Slow because it is the first call](url)
```

With the latest beta version RunCompile is a void method. How can I get the result then?

**Comment by matthid** [comment]
There is large number of overloads. void is returned by those who take a streamwriter argument. What you want is one of the extension methods: https://github.com/Antaris/RazorEngine/blob/master/src/source/RazorEngine.Core/Templating/RazorEngineServiceExtensions.cs#L237
You might want to put `using RazorEngine.Templating` on top of your file.
