### ISSUE TITLE
Known BaseTemplates supporting/stubbing HtmlHelper ++ from ASP.NET?

### ISSUE THREAD

**Issue by fatso83** [Antaris/RazorEngine#383]
I am writing a [little cli tool](https://github.com/fatso83/razor-cli) for compiling the templates in our asp.net app into static markup that can be reused in our internal styleguide, but I [got stuck](http://stackoverflow.com/q/37125726/200987) trying to find a way of "supporting" partials using the common `Html` and `Url` helpers that are prevalent in most partials/view code.

I am fully aware that this is not the concern of the RazorEngine project, but I saw a comment from 2011 on StackOverflow that this was to come in version 3. I can see now that this never came to be, but I was wondering if some of the work that went into this has been carried on by some other sibling-project? Perhaps in the form of some BaseTemplate that is loading the actual assemblies, but mocking out the actual `HttpContext` to make it work outside of IIS (this is what I tried unsuccessfully).

When I say "support" the usage of these helpers I am actually not interested in creating full blown functionality, just enough to not throw an exception at runtime/silently ignore the result when encountering some usage of `Html.Action`,`Url.Route`, etc, as this is obviously not interesting to me for the most part. Seems reasonable that someone else has been wanting to do the same, thus the question.

**Comment by campersau** [comment]
You can create your own template class by implementing `ITemplate` or inherit from the existing `TemplateBase` class. There you can create your own helper functions / objects.

See https://antaris.github.io/RazorEngine/TemplateBasics.html#Extending-the-template-Syntax for more information.

**Comment by fatso83** [comment]
@campersau I am aware of that, and I have done so for a long time :-) But implementing a fair number of these helpers is quite a substantial effort, so if there were any known efforts to point to that would be a good start for a lot of people. As in having a `Antaris/RazorEngine-Extras/` repo with good default implementations. 

Seeing that most people wanting to compile existing Razor templates would need to do this, it does not seem very strange that someone might have published their code.

**Comment by matthid** [comment]
@fatso83 I think that has historic reasons. RazorEngine started in a time where not a lot of people were used to open source in the .net/c# communities. It slowly seems to catch on (as I see pull requests popping up from time to time now). 

so it might be the time to start such an extra project. so please feel free to start one and add the links to the docs via PR :)

**Comment by fatso83** [comment]
@matthid OK, fair enough :-)

Closing for now.
