### ISSUE TITLE
Simplify code for includes

### ISSUE THREAD

**Issue by egdd** [Antaris/RazorEngine#391]
Dear all,

Looking at example [Partial Templates](https://antaris.github.io/RazorEngine/LayoutAndPartial.html#Partial-templates) again, I see that there is the following code:

```
service.AddTemplate("template", @"<h1>@Include(""part"", @Model.SubModel, typeof(TestRunnerHelper.SubModel))</h1>");
```

I want to know why we have to specify here that the included template part is of type "typeof(TestRunnerHelper.SubModel)" when it is being done again two lines later:

```
service.Compile("part", typeof(SubModel));
```

If I remove it in the template code it fails.

My question: Can I get rid of one of the declarations to keep the include-code "cleaner"? Sorry if this question sounds a bit silly, but I'm barely scratching the surface of this cool engine.

Greetings

egdd

**Comment by egdd** [comment]
Dear all,

In [TemplateBase.cs](https://github.com/Antaris/RazorEngine/blob/master/src/source/RazorEngine.Core/Templating/TemplateBase.cs) I found the following method "public virtual TemplateWriter Include(string name, object model = null, Type modelType = null)"


If I put the following code piece at the beginning of th method it works:

```
if(modelType == null)
{
    modelType = model.GetType();
}
```

So instead of:

`service.AddTemplate("template", @"<h1>@Include(""part"", @Model.SubModel, typeof(TestRunnerHelper.SubModel))</h1>");
`

now it's possible to shorten the call to the template a bit:

`service.AddTemplate("template", @"<h1>@Include(""part"", @Model.SubModel)</h1>");
`

Perhaps it's good to include that in the code base?


Greetings

egdd

**Comment by matthid** [comment]
`null` means dynamic and should work. The problem is the following: If you have a shared razor `template` and use the current type as default, it might be compiled several times for no reason. That's why we use `dynamic` as default (which by the way is what MVC Razor is doing as well).

Yeah it is unfortunate but IMHO the only sane default.

**Comment by egdd** [comment]
Dear matthid,

I see. Then my workaround is not a good idea. I try to solve it different then. Thanks for your answer!


Best regards

egdd
