### ISSUE TITLE
Include only works with @

### ISSUE THREAD

**Issue by zoidicus** [Antaris/RazorEngine#397]
The following works:
`<span>@Include("simple.cshtml", "hello world 1");</span>`

...as does this:
`<span>@{
        @Include("simple.cshtml", "hello world 2");
    }</span>`

...but this does not:
`<span>@{
        Include("simple.cshtml", "hello world 3");
    }</span>`

In the 2nd example, I do not believe the 2nd '@' should be required, but the 3rd example does nothing with the Include, and there are no warnings or exceptions.  I thought '@' was strictly for switching context/syntax.  Is this expected?

Version 3.8.2

**Comment by burningice2866** [comment]
@ actually has two meanings

1. Yes, its a context switch between code and html
2. Its a shorthand for doing Response.Write, similiar to = in asp.net webforms

So in your third example `Include` is being called and returns html, but is then discarded since you're not doing anything with it.

**Comment by matthid** [comment]
Thanks @burningice2866 for answering this.
