### ISSUE TITLE
How do I display literal HTML in the output?

### ISSUE THREAD

**Issue by sdg002** [Antaris/RazorEngine#399]
Firstly , Please accept my sincere thanks for this library. We are generating formatted emails using Razor.Parse.

Our simplified scenario is as follows:
```
var model= new {ID=102, Name="John Doe", Bio="<strong>some rich text</strong>"};
var output=Razor.Parse(htmlTemplate,model);
```

The resulting HTML has encoded the contents of the property **Bio**.  The angular brackets in the property **Bio** have been replaced by **lt** and **gt**.
We would like the HTML content of the **Bio** property to be emitted as literal HTML and not get escaped.

Is this possible?

Thanks,
Saurabh

**Comment by aviatrix** [comment]
you can use the  `@Raw()` method :)

**Comment by kobruleht** [comment]
@{WriteLiteral("<h1>Test</h1>");}

also works
