### ISSUE TITLE
RawString Bug.

### ISSUE THREAD

**Issue by xiaolu6t** [Antaris/RazorEngine#401]
`@if(Model.hasGenericType){
			if(Model.isDeclaration){
			@:List<@{@Model.type}> @{@Model.varName}=new List<@{@Model.type}>();
			}
			}else{
			@:var @{@Model.varName} = new List<__@{@Model.functionName}_@{@Model.varName}__>();
            }
            //Compute Sql statement
			__@{@Model.functionName}_@{@Model.varName}_command__ = new System.Data.SQLite.SQLiteCommand(string.Format("@{@Model.pageSql}",@{@Model.pageVarName}.size,(@{@Model.pageVarName}.index-1)*@{@Model.pageVarName}.size), @{@Model.connectionVarName});
			@if(Model.isTransaction){
			@:__@{@Model.functionName}_@{@Model.varName}_command__.Transaction=@{@Model.transactionVarName};
			}`

			__@{@Model.functionName}_@{@Model.varName}_command__ = new System.Data.SQLite.SQLiteCommand(string.Format("@{@Model.pageSql}",
recognition error!

**Comment by matthid** [comment]
@xiaolu6t Can you write a self contained failing test case please? I have no idea what you are trying to say here. Maybe github formatting is in the way as well...

**Comment by matthid** [comment]
Closing old issue.
