### ISSUE TITLE
The name 'Context' does not exist in the current context

### ISSUE THREAD

**Issue by ruanpelissoli** [Antaris/RazorEngine#407]
I keep getting this message when I use RazorEngine.Templating.TemplateBase as base page type
or when views inherits RazorEngine.Templating.TemplateBase< MyModel >.

![alt message](http://i.imgur.com/ac589fz.png)

My Web.config:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <configSections>
        <sectionGroup name="system.web.webPages.razor" type="System.Web.WebPages.Razor.Configuration.RazorWebSectionGroup, System.Web.WebPages.Razor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35">
            <section name="host" type="System.Web.WebPages.Razor.Configuration.HostSection, System.Web.WebPages.Razor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" requirePermission="false" />
            <section name="pages" type="System.Web.WebPages.Razor.Configuration.RazorPagesSection, System.Web.WebPages.Razor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" requirePermission="false" />
        </sectionGroup>
    </configSections>
    <system.web.webPages.razor>
        <host factoryType="System.Web.Mvc.MvcWebRazorHostFactory, System.Web.Mvc, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" />
        <pages pageBaseType="RazorEngine.Templating.TemplateBase">
            <namespaces>
                <add namespace="MyApp.Models" />
            </namespaces>
        </pages>
    </system.web.webPages.razor>
    <system.web>
        <compilation targetFramework="4.5.2">
            <assemblies>
                <add assembly="System.Web.Mvc, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
            </assemblies>
        </compilation>
        <httpRuntime targetFramework="4.5.2" />
    </system.web>
</configuration>
```

Couldn't find any solution for this problem, have an idea?
Thanks.

**Comment by majorimi** [comment]
Hi,

Add this code to your generic TemplateBase class

        #region AspNetCompiler workaround
        //http://razorengine.codeplex.com/discussions/542559

        protected void BeginContext(string path, int line1, int line2, bool something)
        {

        }

        protected void EndContext(string path, int line1, int line2, bool something)
        {

        }

        protected HttpContext Context
        {
            get { return HttpContext.Current; }
        }

        #endregion

**Comment by PranKe01** [comment]
That helped me a lot! Thanks majorimi. Wonderin why this is not included in the docs?!

**Comment by matthid** [comment]
@PranKe01 a PR to the docs is always welcome :)

**Comment by daerogami** [comment]
Is this workaround still necessary for a .NET 4.6 ASP.NET application?

**Comment by binhphanduc** [comment]
For more information https://github.com/Antaris/RazorEngine/issues/476
