### ISSUE TITLE
DisableTempFileLocking = true; but still I get the stderr message "We can't cleanup temp files"

### ISSUE THREAD

**Issue by AllanXu49** [Antaris/RazorEngine#409]
I have the following code:

            config.DisableTempFileLocking = true;
            var service = RazorEngineService.Create(config);
            Engine.Razor = service;

However, still, I get the stderr message "We can't cleanup temp files"

Is there any way to disable the message for good?

**Comment by matthid** [comment]
Please read the http://antaris.github.io/RazorEngine/#Temporary-files section

**Comment by AllanXu49** [comment]
Ah, sorry, I supposed to RTFM before posting :(
