### ISSUE TITLE
config.DisableTempFileLocking = true; but still RazorEngine creates temp files

### ISSUE THREAD

**Issue by AllanXu49** [Antaris/RazorEngine#410]
According to the following link:

http://antaris.github.io/RazorEngine/#Temporary-files

I expect if I have `config.DisableTempFileLocking = true;` then RazorEngine won't create the temp files. I tried that and still I get a bunch of RazorEngine_* files in the TEMP folders. Is that behaviour by design? If yes, then what is the relief that `config.DisableTempFileLocking = true;` provides?

**Comment by aviatrix** [comment]
`config.DisableTempFileLocking = true;` = Disable the LOCKING of the TEMP files. it's not called `DisableTempFileCreation`. 
The variable `DisableTempFileLocking` prevents the temp files from being locked so you can delete them. When `DisableTempFileLocking` is set to `false`, razorengine prevents the files from being deleted which can cause issues if you have too many files(over 9 000, for example) .

**Comment by AllanXu49** [comment]
I see. Then I am not following how it helps with the flooding temp file situation?

With or without DisableTempFileLocking  the library ends up with a pile of temp files that fills the disk eventually. Either way, the RazorEngine cannot clean after itself.

 I have to schedule a PowerShell script that does the cleanup after RazorEngine.
