### ISSUE TITLE
Using System.Collections.Immutable library causes an exception in templates using System.Collections.Generic collections

### ISSUE THREAD

**Issue by rickboyce** [Antaris/RazorEngine#415]
Using RazorEngine 3.9.0 on .Net 4.5

We have a template that instantiates a `Dictionary<,>` from `System.Collections.Generic` which was working fine. We recently added the `System.Collections.Immutable` package (v1.2.0 from NuGet) to one of the projects in the solution, so the assembly `System.Collections.Immutable` is now loaded.

This causes the template that instantiates a `System.Collections.Generic.Dictionary<,>` to throw the following exception:

`The type 'System.Collections.Generic.Dictionary```2<T0,T1>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Collections, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'`

The immutable collections are not used within the template, they have been added to a separate project in the solution only and are not exposed to the templates directly.

Making no other change than removing the `System.Collections.Immutable` reference causes the affected template to begin working again.

**Comment by matthid** [comment]
Uh, this might be due to how we add references. We add references to all loaded assemblies when compiling the template.
You can change this behavior via a custom `IReferenceResolver` implementation, please see https://antaris.github.io/RazorEngine/ReferenceResolver.html
