### ISSUE TITLE
 'Html' does not exist in the current context

### ISSUE THREAD

**Issue by shaojun** [Antaris/RazorEngine#417]
Hi,
     I've setup a simple test program (ASP.NET WEB API 2 self host) for using the awesome RazorEngine, the template **Test.cshtml** is really simple and the purpose is to use some Html related helper function which under `System.Web.Http`:
```
@using System.Web.Http
@using System.Web.Http.Controllers
@using System.Web.Http.Description
@using System.Collections.ObjectModel
@using System.Web.Mvc.Html
@using HelpPageForSelfHost.Areas.HelpPage.Models
@using System.Linq
@using System.Web.Mvc
@model Collection<ApiDescription>

@{
       Html.DisplayText("hello world");
}
```

but it always popup run time error of  **'Html' does not exist in the current context**, I've follow the exception detail to open the generated temp file which content listed below:

```
namespace CompiledRazorTemplates.Dynamic
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Http;
    using System.Web.Http.Controllers;
    using System.Web.Http.Description;
    using System.Collections.ObjectModel;
    using System.Web.Mvc.Html;
    using HelpPageForSelfHost.Areas.HelpPage.Models;
    using System.Web.Mvc;


    [RazorEngine.Compilation.HasDynamicModelAttribute()]
    public class RazorEngine_ae6f05352f074401bc906e7f983132d1 :
        RazorEngine.Templating.TemplateBase<Collection<ApiDescription>>
    {



        public RazorEngine_ae6f05352f074401bc906e7f983132d1()
        {
        }

        public override void Execute()
        {
            // below line has the Error, IDE marked with red under line which indicate Cannot resolve symbol Html
            Html.DisplayText("Hello World");
        }
    }
}

```

anything i've missed?

thx.

**Comment by jljaleahy** [comment]
Hello,

Did you ever get this working... I am having a similar issue using Highsoft.Web.Mvc.Charts

This is the code:

@(Html.Highsoft().Highcharts( new Highcharts { .... rest of code here

This is the error:

error: (3978, 35) The name 'Html' does not exist in the current context
Thanks for any help in this matter.
