### ISSUE TITLE
@Html.Partial()

### ISSUE THREAD

**Issue by jeeRyes** [Antaris/RazorEngine#420]
I just got the recent RazorEngine version, and I am  trying to use it. I have hit a roadblock of finding a good substitute for @Html.Partial. 

I see the below reply of 'matthid' in stackoverflow: http://stackoverflow.com/questions/26553670/how-to-parse-a-razor-template-with-partials-from-a-custom-folder

So I went about creating MyHtmlHelper based on this link: https://matthid.github.io/RazorEngine/TemplateBasics.html#Extending-the-template-Syntax 
```

public class MyHtmlHelper
	{
		public IEncodedString RazorRaw(string rawString)
		{
			return new RawString(rawString);
		}

		public MvcHtmlString RazorPartial()
		{
			return new Include();
		}
	}

	public abstract class HtmlSupportTemplateBase<T> : TemplateBase<T>
	{
		public MyHtmlHelper RazorHtml { get; set; }

		public HtmlSupportTemplateBase()
		{
			this.RazorHtml = new MyHtmlHelper();
		}
	}
```

I realized that my existing templates use @Html.Partial() which returns a MvcHtmlString; however Include() returns a TemplateWriter. I have a few questions pertaining to the code:

1. To begin with how can I access the Include() inside my helper class? In the above code "return new Include() is only partially written. I am trying to finish the RazorPartial().
2. If I am using a TemplateManager as suggested here: http://stackoverflow.com/questions/29803561/razorengine-error-trying-to-send-email, do I need to load all my partial templates into the manager?
3. I cannot use @inherits in my templates, so I have set the configuration's BaseTemplateType. However my @RazorRaw or @RazorPartial are unrecognized by the compiler. I do have the correct using clause in the .cshtml.
4. When I use @Raw("sometext"), I get the error "The name 'Raw' does not exist in the current context"

Thoughts?

**Comment by jeeRyes** [comment]
I changed the HtmlSupportTemplateBase abstract class to below; and I am able to access the Include(). Is this good? Are there better options available? Thanks.

```
public class HtmlSupportTemplateBase<T> : TemplateBase<T>
	{
		public MyHtmlHelper RazorHtml { get; set; }

		public HtmlSupportTemplateBase()
		{
			RazorHtml = new MyHtmlHelper();
		}

		public TemplateWriter RazorPartial(string template)
		{
			return Include(template);
		}
	}
}
```

Template code:
```
@using RazorEngine.Text
@using RazE.Custom
@{
	Layout = null;
}

<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title></title>
</head>
<body>
	<h1>Razor Engine testing partial templates</h1>
	@(new RawString("ddd"))
	@RazorHtml.RazorRaw("text")
	@RazorPartial("fifth")
</body>
</html>
```

**Comment by matthid** [comment]
I think you figured it out! Just calling `Include` in your method is fine.
