### ISSUE TITLE
Temporary files are not removed in Mono

### ISSUE THREAD

**Issue by kobruleht** [Antaris/RazorEngine#421]
If called from ASP.NET MVC4 application Mono / Debian Linux , Razorengine creates subdirectories 
in  /tmp folder for every template like

´´´
RazorEngine_d8n001yi.o3z
RazorEngine_dha6o62p.4vl
RazorEngine_vvtdardq.4jf
´´´

each subdirectory contains source code and compiled dll file.

Those directories are not removed.
After some time of usage, large number of such directories appears and disk becomes full.

**Comment by matthid** [comment]
I think there is a lot of information available about this:
- https://github.com/Antaris/RazorEngine/issues/277
- https://antaris.github.io/RazorEngine/index.html#Temporary-files
- https://github.com/Antaris/RazorEngine/issues?utf8=%E2%9C%93&q=is%3Aissue%20temp%20files
