### ISSUE TITLE
Is RazorEngine threadsafe?

### ISSUE THREAD

**Issue by AnderssonPeter** [Antaris/RazorEngine#423]
Im thinking about using RazorEngine in a asp.net webforms project, but im unsure if its threadsafe?
asp.net spawns multiple threads and appdomains (not sure if it recycles the process before it creates a new appdomain).
Are there  any other gotchas i need to look out for when running in asp.net webforms under IIS?

**Comment by matthid** [comment]
Yes, every `RazorEngineService` instance should be thread safe.

**Comment by AnderssonPeter** [comment]
@matthid  Thanks
