### ISSUE TITLE
Binding issue with _@ character combination

### ISSUE THREAD

**Issue by spotvader** [Antaris/RazorEngine#424]
I am getting a binding error when attempting to bind a razor template that has an email address in it using the following structure: 

somestring_@somewhere.com 

The email address itself is a valid one, but the RazorEngine is throwing an exception saying "somewhere" does not exist in the model. It appears the underscore character just before the @ symbol in the email address is causing it to think @somewhere is an attempt to bind to a model property. Does anyone know of a way around this?

**Comment by matthid** [comment]
Can you use `@Raw` like documented [here](https://antaris.github.io/RazorEngine/Encoding.html)?

**Comment by salixzs** [comment]
Try putting two @@. At least it works within string variables.

**Comment by spotvader** [comment]
I am unable to escape the sequence because the email address is piped into a razor template prior to me getting it for binding.  While the suggestions above would fix it if I had control over the value, I do not.  Is there a reason _@ triggers the binding and is treated as a model property?

**Comment by matthid** [comment]
@spotvader That's just how the razor parser works/is defined. You need to provide a template with valid syntax. You either need to fix the part where you pipe the value into the template or post-process the template to get a valid one...

**Comment by spotvader** [comment]
I ended up post-processing the template to replace _@ with _@@, then do the razor biding, then set _@@ back to _@.  A little wonky in my opinion, but it does work.

**Comment by matthid** [comment]
Glad you were able to solve it :)
