### ISSUE TITLE
What is a RazorEngine4?

### ISSUE THREAD

**Issue by DivenLee** [Antaris/RazorEngine#432]
Hello, I see your updates are 3.9.2 and 4.4.2RC1, respectively, is a different framework. So the future is not in the updated version of the RazorEngine3 series? Will only be out of the Core.NET version?
Can I think 3.9.2 is the last version of RazorEngine3?

**Comment by matthid** [comment]
Not sure where we go with RazorEngine4 but RazorEngine3 is all about Razor3 and will probably stay for quite a while. Versioning in this package is difficult because of several reasons.

> Can I think 3.9.2 is the last version of RazorEngine3?

No 3.10.0 will be released soon. Hope this answers this.
