### ISSUE TITLE
Razor Strings from database or File structure

### ISSUE THREAD

**Issue by vyelchuri** [Antaris/RazorEngine#434]
I was trying to implement pulling razor string from database or file structure. When i am running the template facing an error.

_An unhandled exception of type 'RazorEngine.Templating.TemplateCompilationException' occurred in RazorEngine.dll_

Can some one help me with this ?? . I went through all documentation even thought i am unable to get where i am missing.

```

[RazorTemplats.zip](https://github.com/Antaris/RazorEngine/files/619957/RazorTemplats.zip)



 var layoutText = File.ReadAllText(@"C:\Users\yelcdi01\Desktop\RazorTemplats\LayOut.cshtml");
var templateText = File.ReadAllText(@"C:\Users\yelcdi01\Desktop\RazorTemplats\BusinessReport.cshtml");
var service = RazorEngineService.Create();
service.AddTemplate("layout", layoutText);
service.AddTemplate("template", templateText);
service.Compile("template");
var result = service.Run("template");
```

**Comment by matthid** [comment]
Please try to enable http://antaris.github.io/RazorEngine/#Debugging and carefully read the message of the thrown exception.
If you still cannot figure out what's wrong please post the message of the exception.

**Comment by vyelchuri** [comment]
I figured out what is the issue is. It is on my razor template.

Please close this issue.

**Comment by gonself** [comment]
Hi @vyelchuri,

I know is an issue from 2017 but i've the same problem...

Can you describe how to solve this?
Thanks in advanced!
