### ISSUE TITLE
Viewbag values set in Template not returned in Isolated mode

### ISSUE THREAD

**Issue by VinzzB** [Antaris/RazorEngine#487]
I have a problem with my Viewbag when using the isolated mode. The values are not returned when new values are set in the viewbag through a template.
I'm using this code to compile and run the code:
```
public DynamicViewBag ViewBag { get;  set; }
private IRazorEngineService razorEngine = IsolatedRazorEngineService.Create(new LanguageEncodingConfigCreator(Language.CSharp,Encoding.Html), SandboxCreator);
public void Execute() {
  var clRef = @"@{ ViewBag.Test = "testing..."; }";
  var clRef2 = @"@(ViewBag.Test)";  
  var value = razorEngine.RunCompile(clRef, clRef, typeof(TModel), model, ViewBag);
  var value2 = razorEngine.RunCompile(clRef2, clRef2, typeof(TModel), model, ViewBag);
  ...
}
```
The viewbag is initialized in the CTOR. ( this.ViewBag = new DynamicViewBag(); )
How can i get the ViewBag from the first call into the second one. (without concatenating the templates...)? The code only works in the non isolated mode. Is this a bug?

**Comment by campersau** [comment]
I submitted #504 which fixes the issue.

In the meantime you can workaround it by using [this dictionary implementation](https://github.com/campersau/RazorEngine/blob/1036048d447abe216b1169a308bd0d589c123b5a/src/source/RazorEngine.Core/Common/CrossAppDomainDictionary.cs) and use it with a custom `CrossAppDomainDynamicViewBag`:

```cs
[Serializable]
public class CrossAppDomainDynamicViewBag : DynamicViewBag
{
    private readonly IDictionary<string, object> _dict = new CrossAppDomainDictionary<string, object>();

    public override IEnumerable<string> GetDynamicMemberNames()
    {
        return _dict.Keys;
    }

    public override bool TryGetMember(GetMemberBinder binder, out object result)
    {
        _dict.TryGetValue(binder.Name, out result);
        return true;
    }

    public override bool TrySetMember(SetMemberBinder binder, object value)
    {
        _dict[binder.Name] = value;
        return true;
    }
}
```
