### ISSUE TITLE
Cannot debug into template when using EmbeddedResourceTemplateManager

### ISSUE THREAD

**Issue by mscrivo** [Antaris/RazorEngine#501]
When using the EmbeddedResourceTemplateManager, I have been unable to get debugging to work.  If I swap out the EmbededdResourceTemplateManager with the ResolvePathTemplateManager, and all other code unchanged, it works fine.

**Comment by robsiera** [comment]
Maybe this might inspire. Then again, maybe not. Sharing it anyway.
https://github.com/mcintyre321/EmbeddedResourceVirtualPathProvider/wiki/Enabling-debugging-for-embedded-razor-views

**Comment by deveshv19** [comment]
Any resolution on this?
