### ISSUE TITLE
config.Language = RazorEngine.Language.VisualBasic causes compile error BC30451

### ISSUE THREAD

**Issue by isolaol** [Antaris/RazorEngine#88]
Dear developers,

An attempt to compile template written with Razor syntax in VisualBasic.NET causes RazorEngine.Razor.Compile to throw TemplateCompilationException. The Errors collection of the exception contains an item with ErrorNumber = "BC30451" and ErrorText = "'Model' is not declared. It may be inaccessible due to its protection level."

The code below (in VB.Net) reproduces the problem.

    Public Class DataModel
        Public Property AttributeX As String
    End Class

    Sub Main()

        ' introduce variables
        Dim template As String
        Dim model As DataModel
        Dim config As RazorEngine.Configuration.TemplateServiceConfiguration
        Dim service As RazorEngine.Templating.TemplateService
        Dim report As String

        Try

            ' set values of variables
            template = "some @Model.AttributeX here..."
            model = New DataModel()
            model.AttributeX = "content"

            ' configure templating service
            config = New RazorEngine.Configuration.TemplateServiceConfiguration()
            config.Language = RazorEngine.Language.VisualBasic ' set language
            config.EncodedStringFactory = New RazorEngine.Text.RawStringFactory ' set output encoding
            service = New RazorEngine.Templating.TemplateService(config) ' instantiate service
            RazorEngine.Razor.SetTemplateService(service) ' ask engine to use configured service

            ' compile template
            ' !!! THIS WILL FAIL !!!
            RazorEngine.Razor.Compile(Of DataModel)(template, "default")

            ' run template
            report = RazorEngine.Razor.Run(Of DataModel)("default", model)
            Console.WriteLine(report)

        Catch exCompile As RazorEngine.Templating.TemplateCompilationException

            Console.Error.WriteLine("ERROR: TEMPLATE COMPILATION FAILED.")

            If Not String.IsNullOrWhiteSpace(exCompile.SourceCode) Then
                Console.Error.WriteLine("----------")
                Console.Error.WriteLine(exCompile.SourceCode)
                Console.Error.WriteLine("----------")
            End If

            For Each item As System.CodeDom.Compiler.CompilerError In exCompile.Errors
                Console.Error.WriteLine("#{0}: {1} ({2},{3})", item.ErrorNumber, item.ErrorText, item.Line, item.Column)
            Next

        End Try

    End Sub

I have referenced RazorEngine.dll 3.2.0.0.

Kind regards,
Olli-Pekka Isola

**Comment by matthid** [comment]
Does this work now with 3.5.0-beta2 (which has support for net40)?

**Comment by matthid** [comment]
Closing this for now as 3.5.X should work (open a new issue or comment here if not).
