### ISSUE TITLE
Nullable Property on Model

### ISSUE THREAD

**Issue by Zetanova** [Antaris/RazorEngine#94]
Hallo!

After update to 3.2.0 nullable properties are threated as there base types.

class Model { public DateTime? Birthday { get; set; } }

@Model.Birthday.HasValue //Exception "Porperty not found"
@Model.Birthday.ToString("d") //working

if the property is null then Service.Run will throw an exception.

 Some similar problem was fixed on Version 3.0.0.0 with:
https://github.com/Antaris/RazorEngine/issues/18

My rendering Code:

```
   public string Parse<T>(string template, T model, string name)
   {
        if (String.IsNullOrEmpty(name))
            name = String.Format("Template{0}", template.GetHashCode() ^ model.GetType().GetHashCode());

        if (!razorService.HasTemplate(name))
            razorService.Compile(template, model.GetType(), name);

        return razorService.Run(name, model, null);
   }
```

**Comment by atsidaev** [comment]
Still exists in 3.5.0.0

```C#
string template = "@Model.Date.Value";
Engine.Razor.RunCompile(template, "", null, new { Date = new DateTime?(DateTime.Now) });
```

**Comment by matthid** [comment]
This is another issue, because of using an anonymous type, right? But I would need to look at that in detail to tell to the exact reason. Does this block you in any way? A workaround seems to be simple enough, but if you feel like this blocks you please open a new issue.

**Comment by matthid** [comment]
Relevant: http://stackoverflow.com/questions/3728752/c-sharp-4-dynamic-and-nullable
So it's clear why the exception is thrown (because type=null means dynamic in the new API) and there is no other way to support anonymous types but to use dynamic.

Hope that helps.

**Comment by atsidaev** [comment]
No, this is the same issue. I used anonymous type just for shortness. For the Model class from the 1st comment we get the same behavior.

```C#
class Model { public DateTime? Birthday { get; set; } }

string template = "@Model.Birthday.Value";
Engine.Razor.RunCompile(template, "", null, new Model { Birthday = DateTime.Now });
```
This can be fixed in many ways so it does not block me, thank you.

**Comment by matthid** [comment]
Just to clear things up:
```csharp
Engine.Razor.RunCompile(template, "", null, new Model { Birthday = DateTime.Now });
```
will not work because it will use dynamic as the model-type. But

```csharp
Engine.Razor.RunCompile(template, "", typeof(Model), new Model { Birthday = DateTime.Now });
```

will work (note the typeof argument instead of null). Note that you need to make the model public.

**Comment by atsidaev** [comment]
Thank you, this is much better than any of my solutions.
