### ISSUE TITLE
Set Default Template Service missing in web.config

### ISSUE THREAD

**Issue by robi2** [Antaris/RazorEngine#95]
Hi,

I noticed that in the previous documentation(on codeplex) you can set the default templating service to be used in the web.config.

Like so:
```
<razorEngine>
        <templateServices default="myCustomTemplateService">
            <add name="myCustomTemplateService" ...
        </templateServices>
</razorEngine>
```

I tried to set this in the new version and got a message that the default attribute is not supported.

Is there still a way to set the default template using the config file?

Thanks,
Robert

**Comment by matthid** [comment]
Closing because outdated, please open a new issue if that is still true.
